### ISSUE TITLE
Edit view UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#1000]
*Edit view behaves the same way as it behaves now. Updates are only UI related.*
- [ ] Tapping on a category opens category edit in the same view.
- [ ] Tapping start/end times opens start/end time editing popup.
- [ ] Map's height depends on the screen size. Map always starts from 22pt below start/stop fields and ends with tab bar.
- [ ] Back arrow takes user back to the timeline.
- [ ] User can also use swipe right to navigate back to the timeline view.

### Edit view and category edit
![edit 1x](https://user-images.githubusercontent.com/5064445/35847798-6512784c-0b24-11e8-9e02-4167e97a48ef.png) ![edit - categories 1x](https://user-images.githubusercontent.com/5064445/36298705-11b95680-1302-11e8-8586-c649c4263083.png)

Zeplin: https://zpl.io/VDp54pg & https://zpl.io/bWB9vLe

**Comment by Odrakir** [comment]
@pe0ny Doesn't it make sense to show the category selector the same way it's shown in the timeline? Meaning over the current category and not under it.

**Comment by pe0ny** [comment]
@Odrakir I agree, I'll make changes accordingly. 👍

**Comment by pe0ny** [comment]
*Update the edit view and Zeplin file*
