### ISSUE TITLE
Why the app is open source?

### ISSUE THREAD

**Issue by amorenew** [toggl/superday#1041]
I wonder how is your business app is open source? I can't understand that.

**Comment by amulware** [comment]
Hey @amorenew,

It's simple really: Here at Toggl, we believe in transparency.

Several of our main apps are open source: [Superday](https://github.com/toggl/superday), [Toggl Mobile](https://github.com/toggl/mobileapp), [Toggl Desktop](https://github.com/toggl/toggldesktop), [Toggl Button](https://github.com/toggl/toggl-button) and we have a bunch of other smaller repositories as well. We do not only share the code, but also the way we work on it publicly. Anyone can read through our issues, milestones, pull requests and reviews, etc.

We strongly believe that this transparency improves communication and trust with our users. Further, it makes working on the code more pleasant for us developers as well:

- We can look at the code without being signing in to GitHub
- Anyone can report bugs and add information so we can fix issues faster
- We can show third parties what we're working on, which can be used for bragging but also to show job candidates what they would be working on

We even get pull requests from our users from time to time, helping us improve the apps that they use every day.

It's really a win-win scenario. :)
