### ISSUE TITLE
Strange behaviour in timeline with long slots

### ISSUE THREAD

**Issue by sofokli1** [toggl/superday#1043]
As it can be seen in the gif below the work slot was added `Today` but the slot above was added 2 days before. the strange thing is that the work slot is shown on all 3 dates.

![Feb-14-2018 11-54-21.gif](https://images.zenhubusercontent.com/5889ba0c51aa2c305772dc8f/4334599a-8d1d-4454-97db-80a950de1278)

**Comment by Odrakir** [comment]
I believe this one doesn't happen anymore​. It was just a temporary effect of all those changes.
