### ISSUE TITLE
Save Motion events to the DB every time the timeline generates

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#1071]
Probably during the `TimelineGenerator` run we need to store motion events since last query into the DB. We might be able to use the current interactor for the migration, but we would need to merge them a little so consecutive motion events with the same activity are merged.

**Comment by sofokli1** [comment]
It would be nice to have the location migrator to run as well so that we can get some location for the details view

**Comment by Odrakir** [comment]
Yesss... But there are more changes needed. I'm afraid this needs a bigger change to the TimelineGenerator.

**Comment by sofokli1** [comment]
the location migrator will only import from logs so it shouldn't be that big of an issue. I am not sure if the new locations are going to be saved moving forward
