### ISSUE TITLE
Stop commute retroactively on app start with no recent location updates

### ISSUE THREAD

**Issue by amulware** [toggl/superday#123]
If the app starts (in the foreground OR from a notification, see #122), and the last location update is more than 25 minutes in the past, and the last timeslot is a commute slot, we should stop that slot at the last location update, and create a new one running since then. The user should not notice this change as it will happen before the UI is shown.

**Comment by willsb** [comment]
As discussed: This change must be handled by the `TimeSlotCreationService`. We need to create a new method and the `UIAppDelegate` must only pump data and let the service decide what to do.
