### ISSUE TITLE
Display an end point to show when the last time slot ended

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#128]
Display an end point to user to make it more understandable where and when last time slot ended. This applies only previous days (not current day).

**Comment by pe0ny** [comment]
Fade last time slot out (only the line) and add end time.

![timeline - superyesterday 1x](https://cloud.githubusercontent.com/assets/5064445/20255336/72ffe5e4-aa44-11e6-8595-7eb62ec180ab.png)

**Comment by amulware** [comment]
Am I correct that the fade is only used for the last entry of a day, if that entry is stopped? And not for the last entry, if it is 'running'?

**Comment by pe0ny** [comment]
@amulware Yes. Only for the last entry of a day if that entry is stopped.
And only for previous days since today's last entry is always running and we'll show a dot there.

**Comment by soundsmitten** [comment]
Once b7a89aba3 is merged, code can be reused to implement the line fade.
