### ISSUE TITLE
Add fade overlay to the bottom

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#129]
![timeline - today bottom fade 1x](https://cloud.githubusercontent.com/assets/5064445/20173053/40439e90-a740-11e6-923f-def75d690250.png)

Check Zeplin for details.

**Comment by amulware** [comment]
A fade at the bottom, but not at the top? Feels inconsistent to me. (Though I would not argue for a fade at the top at all - instead I would look into making the title bar transparent blurry, though I don't know if that is possible while keeping it 'white'.)

**Comment by pe0ny** [comment]
Let's keep top as it is right now. Bottom fade is need though because of the add button there.
