### ISSUE TITLE
Calendar view

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#140]
Currently tapping on calendar icon jumps back to current date and doesn't open actual calendar. That's somewhat confusing for users and they expect calendar to pop out to pick a date. That was initial solution which we would like to improve now.

Here is the calendar view (check Zeplin for more details):
![timeline - calendar 1x](https://cloud.githubusercontent.com/assets/5064445/20590507/2c78dbc2-b22c-11e6-913d-a456e9585fa4.png)

When user taps on the calendar icon, calendar slides down from the top (including calendar header with month, arrows and days row).
Same time white background overlay fades in.
Rows will appear from left to right with short delays.

User can switch between months by using left and right arrow or left/right swipe.
Swipeable area:
<img width="339" alt="screen shot 2016-11-24 at 10 00 55" src="https://cloud.githubusercontent.com/assets/5064445/20590639/04a6ba14-b22d-11e6-8709-67da35d3af5a.png">
When user moves to next month, current month leaves from the screen (from right to left) and next month enters the screen (from right to left).
Moving part:
<img width="302" alt="screen shot 2016-11-24 at 10 13 08" src="https://cloud.githubusercontent.com/assets/5064445/20590934/a0d7b6d0-b22e-11e6-8c99-d316f173238f.png">

To close the calendar user can tap again on the calendar icon, swipe up or tap the area below the calendar.
Area below the calendar:
<img width="349" alt="screen shot 2016-11-24 at 10 02 53" src="https://cloud.githubusercontent.com/assets/5064445/20590671/37fd76aa-b22d-11e6-8dbd-a8d5e06e02be.png">

Current date is highlighted with grey background and using bolder font.

In addition to showing just calendar, we display mini-charts there showing daily summaries. Chart width is 21pt which is equal to 100%. 

_Animations are currently WIP. Additional info and examples coming soon._

**Comment by pe0ny** [comment]
Animations:
[superday-calendar.zip](https://github.com/toggl/superday/files/611344/superday-calendar.zip)

![nov-24-2016 15-00-20](https://cloud.githubusercontent.com/assets/5064445/20599420/c790005c-b256-11e6-816d-4b0fa81c4566.gif)

Curves:
StandardEase = "cubic-bezier(0.4, 0.0, 0.2, 1)"
EnterCurve = "cubic-bezier(0.0, 0.0, 0.2, 1)"
LeaveCurve = "cubic-bezier(0.4, 0.0, 1, 1)"
RetunCurve = "cubic-bezier(0.4, 0.0, 0.6, 1)"
EnterTiming = .225
LeaveTiming = .195
LeaveTimingFaster = .145

### Open calendar

Overlay fade in: StandardEase .225 opacity from 0 to 100%
Calendar background slides down: EnterCurve .225 opacity remains 100%

**Delay .105** Fade in calendar header with month, arrows and days row
Start position is -20pt higher
Move 20pt lower, EnterCurve .225 opacity from 0 to 100%

**Delay .160**
Rows will appear from left to right with short delays. Start position is -20pt to left
```
for n in [0...4]
showRowWithDelay(calendarRows[n], n/20)
```
delay = n/20
Move row 20pt to right, EnterCurve .225 opacity from 0 to 100%


### Close calendar
No delays.
Move rows 20pt higher, RetunCurve .145 opacity from 100% to 0
Move calendar header with month, arrows and days row 20pt higher, LeaveCurve .145 opacity from 100% to 0
Slide calendar background back to top, LeaveCurve .225 opacity remains 100%
Fade out white overlay: StandardEase .225 opacity from 100% to 0


### Choose a date
When user picks a date, date will be highlighted and calendar will be closed.
To highlight a date: LeaveCurve .145 opacity from 0 to 100%
**Delay .1** Remove highlight and close calendar

Remove highlight:
Move it 20pt higher RetunCurve .145 opacity from 100% to 0


### Switch months

**Comment by pe0ny** [comment]
When user can't move backward or forward anymore,
the arrow's opacity should be 20% instead of 100%:

![timeline - calendar 1x](https://cloud.githubusercontent.com/assets/5064445/20717076/fc9e89bc-b65c-11e6-9253-1c0a76d10b91.png)

**Comment by pe0ny** [comment]
* Also, don't show upcoming months, so current month should be the last one.
* Lower bound should be the month when user started using the app.
* User can select only today and dates before that (can't select future dates).

**Comment by amulware** [comment]
This being such a big feature, I would like to release it internally as soon as possible (i.e. this week).
