### ISSUE TITLE
Discarding the feedback form opens the edit

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#165]
When I tap the feedback icon and decide to cancel it: tap "Cancel" and then "Delete draft", then the app opens the edit time slot view which shouldn't happen.

**Comment by amulware** [comment]
I cannot reproduce this. Does this always happen? Does the app have to be in a specific state? @pe0ny

**Comment by amulware** [comment]
Nevermind, I can reproduce it. It appears this only happens if the edit view has been opened at least once before. After that it happens every time.

**Comment by amulware** [comment]
Whether or not we fix this using an alternative to the reactive `Variable` observable, I'd like a solution that is stable and prevents similar issues in the future.

**Comment by willsb** [comment]
Could not reproduce. This might have been collaterally solved by #207
