### ISSUE TITLE
Last onboarding screen disappears after 5 seconds

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#186]
When tap and allow notifications the same screen stays there at least 4-5 seconds before it disappears and I can see the timeline. Is it somehow possible to make it faster because for a few seconds I thought it's broken.

![img_1912](https://cloud.githubusercontent.com/assets/5064445/21055398/f54d28e6-be39-11e6-949f-4a2a41a3be18.PNG)

**Comment by amulware** [comment]
Needs investigation, and fix if possible.

**Comment by amulware** [comment]
I can confirm that the screen stays visible for a noticeable amount of time after dismissing the notification. In fact, sometimes the screen stays visible until I tape it (waiting for up to 20 seconds).

**Comment by amulware** [comment]
Could this be related to #189?

**Comment by amulware** [comment]
Closed through #206.
