### ISSUE TITLE
Superday logs sent by the users

### ISSUE THREAD

**Issue by zdericnina** [toggl/superday#221]
Several cases with Superday logs came in Desk during your vacation.
The cases are: #406999, #407023, #407388, #407476

**Comment by fonorobert** [comment]
also 407618

**Comment by zdericnina** [comment]
#407832 as well and he also sent a feature request "It needs to know about sleep."

**Comment by fonorobert** [comment]
408139 sent logs as well, commented: "How about "family" or "exercise" categories?"

**Comment by vedr4n** [comment]
408168

**Comment by vedr4n** [comment]
409603

**Comment by amulware** [comment]
Don't think we still need this.
