### ISSUE TITLE
Write unit tests for the ViewModels

### ISSUE THREAD

**Issue by willsb** [toggl/superday#230]
We lost our beautiful 100% coverage status. We need MOAR® tests for the VMs.

Please note that this is a list of the tests missing, don't use the items as the names of the tests.

**MainViewModel**
- [x] A new SmartGuess is added if the location service returns a valid location from `getLastKnownLocation`
- [x] The SmartGuess service must strike if a category was wrongly set
- [x] A new SmartGuess is added if updating a category that previously had no SmartGuess associated to it
- [x] The update method marks a TimeSlot as `setByUser`

**PagerViewModel**
- [x] The date observable does not pump new `DateChange`s unless the date changes
- [x] Cover all possible cases for the `shouldRefreshView` method
  - [x] `.inactive` case sets the last inactive date
  - [x] Waking with `.needsRefreshing` sets the date to `nil`
  - [x] Waking with `.needsRefreshing` pumps a new refresh event
  - [x] Waking with `.active` and no `settingsService.lastInactiveDate` does nothing
  - [x] Waking with `.active` in `date == today` does nothing
  - [x] Waking with `.active` in a case that does not fall in the last two sets the lastInactiveDate to `nil` 
  - [x] Waking with `.active` in a case similar to the previous bullet item pumps a new refresh event

**TimelineViewModel**
- [x] The `notifyEditingBegan` method returns the `index`th TimeSlot
- [x] The ViewModel fetches TimeSlots from the service whenever the app wakes up if it's set for the current
- [x] If multiple slots are visually merge, only the last one shows the duration
- [x] If multiple slots are visually merge, the last one shows the duration of all previous merged slots

**CalendarViewModel**
- [x] The `selectedDate` variable pumps new events to the `dateObservable`
- [x] The `currentVisibleCalendarDate` variable pumps new  events to the `currentVisibleCalendarDateObservable`
- [x] The `maxValidDate` returns the current date at all times
- [x] Test all cases for the `canScroll` method
  - [x] Date comes before to install date
  - [x] Date comes after current date
  - [x] Date is valid
- [x] Test all the `getActivities` pipe methods. I won't list those, but it needs 100% coverage for every case of every method in the pipe.

**Comment by amulware** [comment]
@sofokli1 @Odrakir How do you feel about this issue? If you don't really want to do this right now, I'm fine with moving it.

And if there are arguments for not doing this at all, let me know!

**Comment by sofokli1** [comment]
This will be needed at some point but should not block the current milestone. So if this is what is needed for the milestone to finish, better move it somewhere else.

**Comment by Odrakir** [comment]
Ah, tests, love them, hate them... mostly hate writing them. I'll see if I can make some of them for this release.
