### ISSUE TITLE
Trigger notification when user stops commuting

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#24]
Notifications are triggered when user stops commuting and we'll create a new time slot.

If the app detects common place, we won't show the notification, instead add category automatically. The app should be smart enough to compare previous locations where user have been (not exact location but ~200m radius).

**Comment by willsb** [comment]
Notification handling code added by #35. This now depends on the improvements me and @amulware will make for #2. 

Also, @pe0ny, could you add designs/copy for the notifications here?

**Comment by pe0ny** [comment]
Copy for the notification: "Howdy! I’m so excited what you’re doing right now. Would you please tell me?"

![notification - lock screen](https://cloud.githubusercontent.com/assets/5064445/19449248/6f34e1fa-94ad-11e6-90eb-89c622895ff7.png)

When the device is in use, show _banner_ notification which appears at the top of the screen for a few seconds.
When the device is not in use, show notification on the lock screen.
