### ISSUE TITLE
Empty(?) state for disabled location permissions

### ISSUE THREAD

**Issue by amulware** [toggl/superday#36]
As mentioned in #16, the app should show a friendly message in the main view if location permissions are disabled, directing the user to enable them in the settings.

This needs design/copy.

I think we should still allow the user to use the app manually in the meantime however, and not shut people out completely, if they have locations disabled.

**Comment by pe0ny** [comment]
![step5 location not enabled](https://cloud.githubusercontent.com/assets/5064445/19300909/1617f2be-905d-11e6-8952-b45983a684df.png)

**Comment by pe0ny** [comment]
When user taps "Enable location", direct user to Superday settings.

**Comment by amulware** [comment]
@pe0ny This copy sounds a lot like the user just started the app up for the first time (but denied permissions). Should something different be shown on non-first starts (if location is disabled - user could have changed it manually in the settings for example).

**Comment by pe0ny** [comment]
@amulware that's actually for the first time users who didn't allow it at the beginning.
So basically, when other users (who allowed using their location) will see this:
![step5](https://cloud.githubusercontent.com/assets/5064445/19319210/22a7fef8-90ac-11e6-8905-c7f4779914cb.png)

then users how didn't allow it, will see that one instead:
![step5 location not enabled](https://cloud.githubusercontent.com/assets/5064445/19319224/31b8d700-90ac-11e6-8e7b-9800a4684086.png)

and yes. we need another view for non-first-time-users too.

**Comment by pe0ny** [comment]
But when they (first time users) finally enable location, then we'll display them the same thing:
"That's it! Check back later..."

**Comment by amulware** [comment]
What happens if a user - after using the app for some time - disables location services?

iOS actually prompts them to do so, to save battery life. (I hope but can not guarantee that this only occurs when the user does not use the app a lot - still, it will happen to some percentage of users.)

**Comment by pe0ny** [comment]
If user disables location after using the app for some time, then we ask them to turn it on.
We'll give user two options:
* To enable location
* Remind me later

Is user chooses "Enable location", direct user to Superday settings.
If user chooses "Remind me later" option, we'll display the same overlay again to the user in 24h.

In that case we shouldn't shut people out, since they might have some data there already which they want to access. 

![timeline location turned off 1x](https://cloud.githubusercontent.com/assets/5064445/19415992/fe6aaf26-938b-11e6-9b1c-81c251a24e4c.png)

**Comment by amulware** [comment]
Note the following (additiona)l requirements:

If the user clicks 'Enable location' in either of the two cases, and then instead of enabling notifications goes straight back to the app, the overlay should still be visible, forcing the user to either enable notifications or explicitly click 'Remind me later'.

Similarly, the 24h 'dont bother me timer' should only come into affect when the user hits 'remind me later' and in no other case.
