### ISSUE TITLE
Change editing to use its own view controller

### ISSUE THREAD

**Issue by amulware** [toggl/superday#41]
This allows us to remove dependencies and simplify other parts of the code, as well as use a proper one-size-fits-all overlay.

**Comment by amulware** [comment]
Note: the overlay itself should be tap-able which closes it without making a change. (In effect, the gray cancel button can simply be click-through.)

**Comment by willsb** [comment]
It doesn't need to be it's own VC, though. Just a view inside the MainViewController.

**Comment by amulware** [comment]
That's fine too. Most importantly, the code should be in its own file somewhere and be decoupled/encapsulated as much as possible. :)
