### ISSUE TITLE
Write unit tests for the View Controllers

### ISSUE THREAD

**Issue by willsb** [toggl/superday#46]
We need to enforce the VC's behaviour using Unit Tests. PR #45 has some DI goodies that'll help us sort this out, so this issue is blocked until the PR gets merged.

**Comment by amulware** [comment]
This needs a list of missing tests.

**Comment by amulware** [comment]
No argument there.

**Comment by Odrakir** [comment]
How about I close this and we promise to create independent tasks for moving logic to view models in every module? (as we already sort of did for onboarding)

**Comment by sofokli1** [comment]
👍
