### ISSUE TITLE
End TimeSlots during the night

### ISSUE THREAD

**Issue by willsb** [toggl/superday#50]
TimeSlots should be ended in the middle of the night if no action is detected

**Comment by amulware** [comment]
Before implementing this I would like some specs on exactly how this is going to work.

I.e. what conditions/events triggers ending what time slot when?

**Comment by amulware** [comment]
Also makes sure the solution accounts for the device not being moved for more than 24h, also see #54.

**Comment by pe0ny** [comment]
I believe we discussed it during the meeting but I would say that day ends at midnight 0:00. That makes the most sense to me.

If user is still active during that time, we'll start a new day with currently running time slot. Eg I started a new time slot at 23:00 (leisure) and it's running. At 0:00 we start a new day with the same time entry.

If user has not been not active (let's say 1h, we can discuss the duration), we'll stop the time slot at 0:00.
