### ISSUE TITLE
Handle corner case in which there is no data for an entire day

### ISSUE THREAD

**Issue by amulware** [toggl/superday#54]
This probably requires an empty state of some sort.

**Comment by willsb** [comment]
@pe0ny I think you need to take a look at this one. If the user does not move the whole day and also does not manually add a TimeSlot, there's no way for us to know what's going on. I agree that an empty state might be needed

**Comment by pe0ny** [comment]
![empty state](https://cloud.githubusercontent.com/assets/5064445/19416134/ea9e3b48-9390-11e6-9c25-8cf61907a77d.png)
