### ISSUE TITLE
Make every build have a different build number

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#549]
Probably with a script that counts the number of commits.

**Comment by amulware** [comment]
@Odrakir Please resolve or close this.

If you're gonna work on it, please discuss the problem of multiple branches having the same numbers of commits. Either find a different solution or argue that it is not a problem we need to worry about.

**Comment by Odrakir** [comment]
My argument agains that being a problem we should worry about is that we are only going to run into conflicts when building for distribution or beta testing, and as this is done always from the same two branches (develop and master) they'll always be increasing.

The only other time we do a test release from another branch is when force pushing to `test-build` but we do that sparingly enough that it shouldn't cause problems.

**Comment by amulware** [comment]
Fair enough. If you can make it do this automatically on every build, go ahead. Just as long as it is fool proof and sets the build number in all places necessary of course.
