### ISSUE TITLE
Consider not saving commute smart guesses

### ISSUE THREAD

**Issue by amulware** [toggl/superday#550]
Mostly, right now if there are commute smart guesses in locations the user goes to a lot, the whole timeline might turn blue for large parts of the day, which looks very bad.

In general, we may want to change the way we think about movement entirely, and instead of treating it as a category like everything else, treat it as a special thing (at least UI wise).

We already talked about displaying 'commutes' differently, so this would play well with that.

**Comment by sofokli1** [comment]
@amulware can you take a look at the PR?
