### ISSUE TITLE
Location access and HK screen are displayed at the same time

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#583]
Figure out how to handle situation when user didn't give access to location during the onboarding flow and 30min later sees HK screen. I doesn't look very pretty atm.

![image uploaded from ios 3](https://cloud.githubusercontent.com/assets/5064445/26189275/1988d40c-3ba4-11e7-9275-927b7ed519e8.jpg)

**Comment by sofokli1** [comment]
@Odrakir should this be closed
