### ISSUE TITLE
Showing the calendar is a little slow

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#591]
We should check this with the time profiler and see what are we doing there that slows down the presentation (probably something around the initialization).

**Comment by sofokli1** [comment]
from what i see the issues seems to be the large amount of view that is being initialised and manipulated. a collection view with a view per cell (~30), each cell label and activity bar (now we are 30*2 = ~60) and all of these need layout calculations + animations calculations. The delay does not seem too big to attempt any changes at this point in my opinion. Open to suggestions

**Comment by Odrakir** [comment]
You might be right. I'm going to run the profiler and see...

**Comment by Odrakir** [comment]
I see two places where this can be improved:
- First, `onCurrentCalendarDateChanged` is called twice when the Calendar first shows up, this has a layout animation that is very costly.
- Second, getting the activities could (and should) be done in the background.
