### ISSUE TITLE
TTL: Remove/merge small timeslots after merge

### ISSUE THREAD

**Issue by amulware** [toggl/superday#594]
We should look at real data from at least several of us, to see what lengths are problematic.

After deciding the limit, we should add a pipe that merges small slots into larger adjacent ones after the merging pipe.

A key problem to solve is how to keep the meta-data of the changed slots in tact. We do not want to lose locations/categories/smartguesses and have to find a way to resolve conflicts.

**Comment by sofokli1** [comment]
@amulware with merge do you mean merging 2 (or more) consecutive small slots together or merging a small slot with a big one (before or after)? or both?

**Comment by amulware** [comment]
I'm not exactly sure what the best behaviour is. The key requirement is that we do not want time entries below a certain (as of yet undefined) duration.

Maybe it makes sense to merge all small slots up/down into the more similar slot, by some definition?

Ideas?

**Comment by sofokli1** [comment]
if we have a small slot that we want to remove/merge, why try to keep the metadata? I mean, since we are trying to get read of it why should we still care about it? that slot will become whatever the nearby category is, so in a way it will lose its identity.

**Comment by amulware** [comment]
But what if this slot has meta data, and the slot we merge it into does not?

**Comment by sofokli1** [comment]
what if we keep it but just don't show it to the user? So no complicated changes in the pipeline just a filter based on duration when fetching the slots.

**Comment by amulware** [comment]
I don't really understand what you mean? how can we keep data, if we are removing the slots?

**Comment by sofokli1** [comment]
i am saying not to remove it from the database, just don't show it in the timeline

**Comment by sofokli1** [comment]
i feel like no consensus was reached for this issue. not sure how to proceed.

**Comment by amulware** [comment]
I think removing the slots only visually, and not from the database has the exact same effect as simply deleting them: In both cases, the contained meta-data will not be used for smart guesses, if the user edits the timeline.

I propose the following behaviour (to be inserted at the end of the pipeline):

- find the shortest slot that is not the very last slot
- if the slot is 5m or longer, we're done
- if the next slot is not directly following this one (overnight behaviour), simply delete the short slot
- otherwise, merge the short slot into the slot following it (i.e. replace both by a slot that takes up the duration of both)

When merging, take the location, category, smart guess (and other data if I forgot any) from the slot with the 'better' meta data. 

'Better' being defined as:
- if both slots have a smart guess, the slot with the more accurate location
- if only one slot has a smart guess, that slot
- if neither slot has a smart guess, merge per field:
  - take the more accurate location of the slots (`nil` being the worst location possible)
  - if the slot which location was taken has a category, take that category
  - if it does not have a category, take the category of the other slot
  - if neither slot has a location, but one of them has a category, take it
  - if both slots have categories, take the one of the longer slot

The only issue I see with this is weird interactions with sleep and commute slots, which are detected differently than other categories. Maybe those categories should never be overriden? Or if one of those is involved, maybe we should always take the data from the bigger slot?

If we _really_ can't come to an agreement, then I would be ok going for merging slots like I described above, and always calling the larger slot the 'better' one.

Thoughts?

**Comment by sofokli1** [comment]
now that we removed the small commutes, how many of these small slots do we get? 

is this really needed?

apart for this needing some work to get done, we still have no clear idea on what is a small slot. 30sec? 2min? And not sure if we need to remove them at all.

maybe the users whent down stairs bought a coffee and came back. like 2min commute + 1min shopping (or unknown if we didn't guess) + 3m commute back (it's 1min longer because they are drinking and walking now 😛 ). it might not look great in the end but it's reality.

This looks more like somtething to discuss in #649

**Comment by amulware** [comment]
This issue is not for fixing the tracking overall, but just to reduce visual noise in the timeline. We should in the very least remove time slots that are <2 minutes. I'd say, even <5.

For what it's worth, in your example, it would merge the shopping into the commute following, and the previous commute into the same slot then. Ending up with a 6 minute slot of either shopping or commute category, which I think is decent. It doesn't do our users much good to get a minute to minute breakdown, if we don't show more data in the timeline, which we are not planning to do as of now.

**Comment by Odrakir** [comment]
I agree with Paul, slots shorter than a certain time (5 minutes seem ok), should be treated as possible breaks, but not as slot themselves. If I go to pee in the middle of my work morning I most likely don't want to track that, at most, I would like to split my morning in before/after I pee.

**Comment by sofokli1** [comment]
you might not care for your pee tracking but we don't know if that makes sense for everyone. (if we can track that we can give kidney status reports to the user 😛 ) what if you go and buy a pack of cigarets, should that count (either as commute or fitness or unknown)?

**Comment by Odrakir** [comment]
I know it won't apply to everyone, there'll be people that will want to track every second, but let's use common sense and settle for something more manageable.

**Comment by sofokli1** [comment]
there is already a small commutes removal PR that has passed review. so we are talking about non commutes at this point. how many of those do you get?

**Comment by amulware** [comment]
The short commute PR is related to HK generation. This issue is related to making the final merged timeline prettier. The problem is that the different sources will not have the exact same time stamps, but close enough to result in tiny 'transition' slots that are silly to keep.

So yes, we get them, and yes we want to merge them.
