### ISSUE TITLE
Switching between previous periods

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#6]
User can switch between previous periods (eg yesterday, day before that etc) by swiping left and right. When user is on current day, then swipe left (to the next day) doesn't do anything. User must always have ability to jump back on current day.

**Comment by willsb** [comment]
Question: How further can users go back? The day they started using the app? The day the app was launched?  1/1/1970?

**Comment by pe0ny** [comment]
Yes. At the first version user can swipe back until the day he/she started using the app. But keep in mind that in the next versions we want to use some more reasonable solution (eg user can swipe back one week and/or switch to exact date/week).
