### ISSUE TITLE
Collapse merged time slots

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#620]
Visually collapse merged time slots with same category by default like this:
![yesterday collapsed slots 1x](https://user-images.githubusercontent.com/5064445/27135460-3097c9fe-5121-11e7-9246-f8c958bfdd71.png)

When user taps on the three dots, show visually merged time slots like we did before, but with option to collapse slots again:
![yesterday merged time slots 1x](https://user-images.githubusercontent.com/5064445/27135476-35ed75c0-5121-11e7-88bc-ee2efda9c321.png)

note! collapsed slot height: 20pt first slot, 3 dots 4pt height, 20pt last slot

**Comment by amulware** [comment]
I hope the default animations will look good here. Otherwise we may have to think about doing something custom.

**Comment by Odrakir** [comment]
Couple notes/questions/points to be in the same page:

- The line height when collapsed should behave the same as for normal time slots, shouldn't it? In the mock up it seems it's too short for a 3:25 TS.
- To make implementation easier I'll make it so the default state is always collapsed for TS with the same category, if you expand any of them, the app won't remember which ones you expanded (maybe even have just one block expanded at a time)

**Comment by amulware** [comment]
@Odrakir according to the above:

> collapsed slot height: 20pt first slot, 3 dots 4pt height, 20pt last slot

('slot height' referring to the height of the coloured line)
I think this answers your question? If not please elaborate.

I agree there is no need to remember the collapsed state, and collapsed should be default.

**Comment by Odrakir** [comment]
Oh, I'm sorry, didn't read that part. Then the question is: Why not make it grow more than that? I mean, that way a collapsed slot of 30 min total will look the same as one of 4 hours total...

**Comment by amulware** [comment]
Ping @pe0ny.

**Comment by Odrakir** [comment]
Also: What happens when a user edits a grouped timeSlot? Is he editing all the sub-timeslots?

**Comment by Odrakir** [comment]
More: If the grouped slots are the last ones in today... Wouldn't it look a little strange to have the 3 dots  indicating grouped slots and then another 3 dots indicating it's still running? Can I see a design of how would that look?

**Comment by pe0ny** [comment]
@Odrakir 

> Also: What happens when a user edits a grouped timeSlot? Is he editing all the sub-timeslots?

Yes.

> More: If the grouped slots are the last ones in today... Wouldn't it look a little strange to have the 3 dots indicating grouped slots and then another 3 dots indicating it's still running? Can I see a design of how would that look?

That's really good point! It might look a bit strange indeed. In that case I would say we should switch back to one dot instead to indicate running slot

**Comment by pe0ny** [comment]
> Why not make it grow more than that? I mean, that way a collapsed slot of 30 min total will look the same as one of 4 hours total...

The main idea behind it was to make timeline shorter in general, that's the reason why we don't wanna make it longer
