### ISSUE TITLE
Timeline: Slot sizes

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#621]
To make timeline shorter in general, let's change slots heights:
Slot's min height: 20pt
Slot's max height: 72pt
Collapsed slot: 20pt first slot, 3 dots 4pt height, 20pt last slot
Sleep slot: 20pt

**Comment by amulware** [comment]
Until we have an official answer, let's stick the two limits in the question into constants, and set them to 10 and 60 minutes, and see how it looks. We can see about fine tuning it later.

**Comment by pe0ny** [comment]
@amulware 

> I take it by 'slot' you mean the length of the line representing the duration, not the whole time slot (including icon, etc).

yes

> Are you sure that limiting things so much will still make relative sizes a good intuitive indicator for duration?

yes

> (Alternative: Why not use some sort of function for duration->height that grows less and less as the duration increases?)

it would make sense actually but then duration will always affect the height, right? i mean heights will change when i suddenly have eg 10 hour slot?

**Comment by amulware** [comment]
If such a function was used, yes, the only limit to height would be 24h in the day. The function could stop growing much quickly though, be it an arctan or exponential fall off. Maths. :D
