### ISSUE TITLE
Wrong category buttons layout in chart view for iOS 9

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#626]
![27142162-8eb58a7c-512a-11e7-88e1-4ab148c6e281](https://user-images.githubusercontent.com/724743/27173632-9e77b04a-51b9-11e7-9347-14ab19794637.png)

It's something related to the custom layout. iOS 9 users as of today are 0.03 % of our users.

**Comment by sofokli1** [comment]
i propose to just close this

**Comment by sofokli1** [comment]
@amulware @Odrakir what do you guys think ☝️ ?

**Comment by amulware** [comment]
Agreed.
