### ISSUE TITLE
Add linting rule about opening braces

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#662]
I'm not sure if SwiftLint can do this, I'll investigate. For me ideally braces would be in a new line for classes (protocols, structs, extensions) and methods (functions). For everything else they'd be in the same line (ifs, guards, closures, switch...)

Example:
```swift
protocol MyProtocol
{
    func superFunction()
}

class MyClass: MyProtocol
{
   var whatEver: Bool = false

   func superFunction()
   {
       if whatEver {
           doThis()
       } else {
           doThat()
       }
   }
}
```

But I'm open to other opinions

**Comment by amulware** [comment]
Works for me. But @sofokli1's opinion matters more here.

**Comment by Odrakir** [comment]
@sofokli1 What do you think about this? Are you ok with that format if it can be done in SwiftLint?

**Comment by sofokli1** [comment]
i like the brackets that we were using till now but if you are finding it hard to adjust, lets go with this way.

**Comment by Odrakir** [comment]
Yes please, I find it hard to adjust and also not very consistent in the case of closures. Let me see if SwiftLint can be configured that way.
