### ISSUE TITLE
Allow smart guesses without location

### ISSUE THREAD

**Issue by amulware** [toggl/superday#671]
I see no reason smart guesses without location shouldn't be possible.

Let's think that through!

**Comment by amulware** [comment]
A big question I'm having: how many of our timeslots don't have locations? Maybe we can just make sure all of them do have locations? Except if we have no location updates for hours (or location is disabled). That's tricky.

**Comment by Odrakir** [comment]
For me, with location enabled, only half of my TS have location.

**Comment by amulware** [comment]
This will be part of the smart guess rewrite.
