### ISSUE TITLE
Smart Guesses Threshold

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#672]
We are having a problem with Smart Guesses due, in part, to the time threshold. Right now if there's a smart guess at a specific time, it can suggest it for all time slots within the time threshold of that specific time. This results in having too many slots using that smart guess. For example: If you ate for half an hour at 14:00, and the next day you have 6 unknown slots spanning 10 hours (if the threshold is 5 hours) around 14:00, it'll suggest 10 hours of eating. What's worst, if the user corrects all but the one that's right, it'll then strike the smart guess and won't use it again.

This could be maybe fixed by taking into account also the duration of the smart guess and only propose it for as many slots as to more or less fill that duration... This, of course, needs a lot of reworking in the smart guess system.

**Comment by Odrakir** [comment]
Maybe a different approach could be to take the day as a whole, probably after the day ends and probably taking into account how many edits did the user do as a measure of how correct the day was.

But this is a whole other deal...

**Comment by amulware** [comment]
I think this is overthinking it too much for now. Ideally, there should be many samples (as many as possible really, we could think about how to do that, maybe generate data points when guessing?) in which case this special case should not happen.

**Comment by amulware** [comment]
We will rewrite smart guessing, so this is out of date.
