### ISSUE TITLE
Location last tracking

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#674]
(Following with the discussion in #649)

As discussed previously in GH and Slack, in my opinion we can simplify the whole tracking thing if we separate location tracking from movement tracking (HealthKit or CoreMotion). This implies that the app wouldn't work without HK or CM enabled (CM is much less intrusive than HK or Location in my opinion), but we could always fall back to the current location algorithm if someone is not willing to give CM permissions (but I think it's unlikely that user's will give Location and not CM permissions)

My idea is to first generate a timeline from the CM events, this timeline will mainly just split the day in timeslots depending on movement. Right of the batch we can detect vehicular motion (car, bus, train, metro), running, walking and cycling with a lot of accuracy (been testing that a lot). This will result in a timeline in which we have some slots with categories set (and we are pretty sure they are correct) and some "still" slots with no category.

Then we take the Location data. We can set up SLC or Region Monitoring, but I found out that region monitoring creating a new region every time the user exits the current one is more precise and gives us more updates. With those registered location updates we set the location for EVERY time slot previously generated. A time slot is always in the last location registered before its start time.

This will give us enough information for smart guesses on every time slot. And maybe even help us better identify some of the categories as commute, but I found this is not needed as CM is already VERY accurate with that.

The best part about using CM instead of HK is that the API is much much easier, so it encourages a lot of testing and trying out new things. I've been filtering and exploring CM events time and time again and the iteration cycle is very fast.

I could even create an app in which we can input our day manually as the day goes by and compare it to the automatic generated timeline given different configuration parameters (thresholds and such). Given the current state of my tests it wouldn't take me more than a week. The idea being, we could use that app to find the best setup for tracking.

For example, for me the other day, from this raw data from CM: https://gist.github.com/Odrakir/f05ed2b0cad4bf8975249317ee8b532e

After some filtering (3 passes) I got this:
https://gist.github.com/Odrakir/e4e983b8cc3fc9c45e99539d89d7c7fd

Which is already pretty accurate, but could be further improved with more filtering and adding location. If you notice the "auto" for 2 hours at 11:04:55, that's completely precise. The same as the "run" at 13:25:27, which matches to the second my Nike Running app. 

After 15:50 or so, I got to the library to work and then the walking is just for some seconds, probably just picking the phone for some testing, so we can see what to do with those slots, if we should ignore them or use them as "dividers" from the other slots. The important thing is with this setup is easy to experiment, and if I can build that app we could all try different params.

Finally you can clearly see I left the library at around 20:00, when I started walking more again. You can check slack to see the time matches :)

**Comment by amulware** [comment]
This is not effectively implemented.
