### ISSUE TITLE
Feedback Option Issue

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/superday#681]
Multiple tickets have been submitting empty feedback emails, and two have responded to our "empty feedback" response with the following scenario:

-User taps on the feedback icon wondering what it is
-When the email draft opens, there is no "Cancel" option, so they have to send an empty email.

Was unable to recreate personally, but a user noted that quitting and reopening the app solved the issue.

Example case 515878

**Comment by sofokli1** [comment]
this should be fixed in PR #687
