### ISSUE TITLE
Ask user to upvote/downvote the timeline

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#694]
Ask user to rate the timeline quality (how accurate was tracking and category guessing) by giving thumbs up or thumbs down on every evening.
- Show upvote/downvote option at the bottom of the timeline.
- User gets notified about the option once per day via notification. (let's send notification at 6pm)
- Notification copy: '**Rate your experience** - Did the app track your time accurately?'
- Tapping on a notification opens the app and scrolls user at the bottom of the timeline.
- Don't show this notification on Sundays. Voting is still available on Sundays.
- User can't change upvote/downvote after being already voted.
- Show 'Thank you' note after voting. Remove 'Thank you' note when app goes in the background or when user closes the app.
- User can rate days in the past as well.
- User can't turn this option off.
- Limit voting to last 7 days.

**Comment by pe0ny** [comment]
![daily rating 1x](https://user-images.githubusercontent.com/5064445/28935958-ceb68046-788e-11e7-8bd7-791fcf0f4150.png)

**Comment by Odrakir** [comment]
How does the timeline behave? Does it go under the review message or it just ends before it? And if it goes under... is it a clean cut or do we use a gradient?

**Comment by Odrakir** [comment]
Also... this is for the current day, with the add button... Were we gonna ask for these in the current day or only for the last one?

**Comment by pe0ny** [comment]
I think it's better to ask feedback of today's timeline because that's what user remembers the best (how accurate it was or wasn't). Also, when we add this at the bottom of today's timeline, we don't need to annoy users with notifications - assuming they will open the app once per day anyways. I would show this around ~6pm
But I'm up for discussions :)

Also, if user didn't vote for today's timeline, i would keep it there anyways (maybe they will open the app in the next day and wanna vote).

About the behaviour - timeline does not go under the review message. It should end before it.

**Comment by sofokli1** [comment]
`assuming they will open the app once per day` that's a big assumption. That would be possible if we were making a chat app 😄

**Comment by Odrakir** [comment]
Maybe we can show that message for the last hours of the day (or from around 6pm as you said) and then, for the first hours of the next day, or maybe just the first time the user opens the app in the next day, if he hasn't rated, show the previous day with the rate message.

Also, I would consider not showing the "+" button while the rate message is on the screen, just to gain space.

**Comment by amulware** [comment]
I prefer the behaviour we discussed in the meeting where users can rate days in the past as well, and get notified once per day by notification (which can be set to weekly only).

**Comment by pe0ny** [comment]
But don't you think it will get super annoying if you will get the very same notification every day at the same time? Assuming that user opens the app is actually not an assumption, our daily active users do open the app once per day.

I also have second thoughts about the settings - with every setting option i feel we should make a decision, not let users do decide what/when they wanna see. I believe they would like to turn both of these off. 😄

**Comment by amulware** [comment]
The notification could only show up if the user hasn't looked at the app in the proceeding ~8 hours (or whatever time we think is best)

And I would not allow users to turn off weekly notifications unless they go into the actual settings and block notifications entirely. I think we should use this to remind people that we're still there and have been doing work for them in the background.

And I'm not sure where you get the info from that our users are opening the app daily. Sure, some do, but most probably don't, as you can see by the quickly dropping DAU numbers after the recent spike.

Also, only 3% of our users open the app 6-7 days a week. But maybe I'm missing something here.

But it's your decision. I'm just surprised at the change.

And at least for my part, I would like the app to remind me at least every few days. I'm a busy man after all. :P

**Comment by Odrakir** [comment]
I have to agree with you about giving users the less configuration options possible. Also, it's a very Steve Jobs thing to say: Users don't know what they want. That said, some settings inside the iphone settings make no harm, in my opinion, as they are hidden enough. 

But we still have to set up the app with the default settings we think are best. I'd say showing the feedback everyday in the app, but pushing a notification only after x days have passed without feedback. ¿x = 3 maybe? 

Also, there should be a way to stop it once we have all the feedback we want from that or all users, no point on keep of bothering them.

**Comment by pe0ny** [comment]
@amulware DAU = users who open the app at least once per day. yes, no?

But let's not over complicate stuff and keep the notifications (once per day) and see what happens. If users starts complaining we can think of something else.

> Also, there should be a way to stop it once we have all the feedback we want from that or all users, no point on keep of bothering them.

@Odrakir Good point! New update is the only way i believe?

**Comment by amulware** [comment]
DAU = daily active user, yes. it's a term fabric uses

**Comment by Odrakir** [comment]
Not the only way, it's the simplest though. I was thinking more on: If the user already gave us 10 reviews, stop asking.

**Comment by amulware** [comment]
It says that there won't be a notification and voting options on Sunday. But what if on Monday they look back at Sunday - can they vote now? If not, why not? - Or in general, what is the reasoning behind not letting them vote on the Sunday timeline? (I get the notification because of the weekly one.)

**Comment by pe0ny** [comment]
I corrected the spec - notification is off on Sundays but users can still vote. And if users look back at Sunday, on Monday, then yes, they can vote as well. Reasoning behind not notifying users on Sunday is simply because of weekly rating notification. I don't wanna send them two similar notifications per day.

**Comment by sofokli1** [comment]
@pe0ny just to be sure. The upvote/downvote ui scrolls with the timeline, right?

**Comment by pe0ny** [comment]
@sofokli1 upvote/downvote ui behiaves basically like time slots. when you scroll at the end of the timeline, only then you'll see that. meaning, it's not at the top of the timeline
