### ISSUE TITLE
Fill gap between midnight and first timeslot of the day

### ISSUE THREAD

**Issue by amulware** [toggl/superday#695]
Of course only if there is one. I think in most cases it makes sense to set this to `sleep` automatically, but I'm not sure what to do with people that stay up till 1am or something.

Ideas/suggestions welcome.

In either case, it would be nice if we could reach a 24h coverage of each day, just so that no time is 'lost' when looking at statistics.

**Comment by Odrakir** [comment]
I think it's ok to fill the entire timeline. If there's a big slot of inactivity around night time, the smart guess engine should identify it as sleep easily, shouldn't it?

**Comment by amulware** [comment]
How would it do that? It's not like it takes length into account, and if we just create a magical slot to fill the gap, we don't have a location either. :/

**Comment by amulware** [comment]
We know if the user is sleeping from healthkit.. are we ignoring that data? if so, maybe it's time to use that, and fill in remaining gaps with smart-guessed stuff, or whatever. But I don't wanna go too complicated on this one if we don't have t. :D

**Comment by Odrakir** [comment]
Sorry, I meant it should, not that it does right now. But ideally, with the changes we have in mind that should be easy and in my opinion better than creating a specific case for this. 

HK identifying sleeping only works for users with watches or whatever that tracks sleeping, right?

**Comment by amulware** [comment]
It should work if bedtime is enabled I think. Which I imagine it is for a decent percentage of users?

But I agree, better not to have more special cases.

**Comment by Odrakir** [comment]
Anyway, yes, I think we are ignoring them right now. Not on purpose, I think we are just creating the first slot when there's some activity. I'll check that.

**Comment by amulware** [comment]
Maybe it would make sense to just set this new slot to the same category (and location and smart guess maybe even?) as the one before midnight - since that is the one that we are cutting up. That way working until 1am will be recorded correctly, and so will sleeping, if we go to bed before midnight.

**Comment by Odrakir** [comment]
I agree that all TS should have a location, and that location should be the last one registered. About smart guess... all should have their own, because it's supposed to be time dependent.

**Comment by amulware** [comment]
Makes sense!

**Comment by sofokli1** [comment]
If the user has a watch or bedtime than our job is done, there should be a sleep slot.
(the logic that follows is a bit backward so bear with me)
Else, we should count as sleep from the first time slot of the next day up to the last movement based slot of the night before or cap it at an average of 9h whichever is smaller. if there is still time remaining between the beginning of the sleeps slot and the end of the last slot of the night before we should fill with unknown (or smartguess what that might be).

Day should end when the sleep slot starts (ex: 11pm, 1am, 3am) (not at 12) and if there is no sleep slot then use midnight.

Also since we humans are not perfect creatures, we do not conform to the 24h day thing exactly. In my opinion we need to measure daily charts from the beginning of the sleep slot to the beginning of the next sleep slot (or `now` if still in that day). If any of the 2 sleeps slots is missing use midnight.

Does this make sense?

**Comment by pe0ny** [comment]
👍  I agree that we should define a day / measure daily charts from the beginning of the sleep slot to the beginning of the next sleep slot.

Should we also consider that some people might take a nap during the day and not count that as a 'next' sleeping slot?

**Comment by sofokli1** [comment]
of course we will let them nap during the day 😄

**Comment by amulware** [comment]
Are we talking about completely redoing the way we handle 'midnight'/day transitions? because I think that is much too complicated and certainly out of the scope of this issue.

In fact, it defeats the point of this issue, which was to make each day have 24 hours for statistics.

**Comment by amulware** [comment]
If we were to change our definition of 'a day', that is a different issue, and we would need an exhaustive design and discussion of the consequences and corner cases.

**Comment by pe0ny** [comment]
@amulware can you give some examples which design changes should we make?

**Comment by amulware** [comment]
I'm not talking about graphical design, but functional. This change would have many side effects, and in general, significantly complicate the way we render the timeline and handle data. I'm opposed to it for those reasons. We have other priorities.

**Comment by Odrakir** [comment]
I'm with Paul here. I think the day has to end at 12, we shouldn't try to reinvent the wheel. And as for sleep slots... What makes them different from any other slot? Shouldn't them just be smart guessed?

**Comment by amulware** [comment]
@Odrakir I think that's what we basically said above, yeah. Keep it easy, just fill in the gap. Nothing fancy.

**Comment by pe0ny** [comment]
I think the idea behind it was that atm daily summary (especially 'sleep' cateogory) doesn't make much sense when your day ends at midnight.

**Comment by Odrakir** [comment]
I'm not sure I follow... In mi mind every day will start with a big sleep slot, then all the other slots of the day, and finally a smaller sleep slot (if you go to be before 12).

**Comment by amulware** [comment]
I don't follow either, but we can't guarantee any of that, and I don't see why we would make assumptions. The problem that this issue is about is that we have less than 24 hours of data on many days. This is easily fixed by filling the gap with a slot. Anything else: somewhere/somewhen else. :P

**Comment by pe0ny** [comment]
@Odrakir but if your day starts with a big sleep slot (eg 8 hours) and ends with a short sleep slot (eg you go to bed at 10pm, 2hour slot then), daily summary shows that you had 10 hours sleep that night. but actually it sums up last night's sleep and next night's (few hours). in that case it is not accurate. or did i miss anything?

what i meant was that if we define a day from the beginning of the sleep slot to the beginning of the next sleep slot it would be more accurate if you wanna know how many hours did you sleep

**Comment by pe0ny** [comment]
just an idea: can we end the day at midnight if user (or HK) didn't start a sleep slot before midnight?

if user (or HK) did start a sleep slot before midnight, we end the day then (when sleep slot started), and sleep slot will go into the next day.

does it make any sense?

**Comment by amulware** [comment]
Let's continue that discussion there: #704

**Comment by sofokli1** [comment]
@amulware would it be an acceptable solution to add a pipe that breaks slots (that start before midnight and end after midnight) into 2 slots so that the second slot can be used in the timeline of the next day? With this solution all days will end at midnight and will start at midnight. Both slots will share all data like category, smartguess etc.

**Comment by amulware** [comment]
That might be ok. I'm just wondering if we maybe should smart guess separately... but that might be something for when we rework smart guessing entirely, so yeah, for now, this seems fine.
