### ISSUE TITLE
Ask user to give five-star rating

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#696]
Ask user to rate tracking accuracy and smart guessing at the end of the week (on Sundays at 6pm).
- User will get notification which directs him/her to the app and opens popup so user can give 5-star rating. If notifications are disabled, user will see a popup next time he/she opens the app.
- Notification copy: 'Rate your experience - Please let us know how accurate was your last week’s timeline.'
- Show this notification and popup only on Sundays.
- User can't change the rating afterwards.
- Display weekly summary (use daily summary's template) to show how user's week looks like.
- Show rating popup first time when user has had at least a full week starting from Monday. Eg when user started using the app on Tuesday, show the popup next week on Sunday.
- Show 'Thank you' note after rating. Remove 'Thank you' note when app goes in the background or when user closes the app.
- User can't turn this option off.
- User can close the popup.

**Comment by pe0ny** [comment]
![weekly rating 1x](https://user-images.githubusercontent.com/5064445/28935985-e30593c0-788e-11e7-93a2-58796f1644b3.png)

**Comment by Odrakir** [comment]
Heidi, this is just my personal opinion, but... given the constrained space... Are you sure we need so much text? It feels like it could be done clearly enough with just one line "Rate your timeline accuracy" or whatever.

**Comment by pe0ny** [comment]
But don't you think if we just say something like: 'Please rate your timeline accuracy' it's a bit confusing if we also show weekly summary there as well? If we would just ask them to rate the app in general, then i would agree. But I feel we need to emphasize a bit more that we wanna know about *this* week.

**Comment by Odrakir** [comment]
"Rate your last week's timeline accuracy" ? 😁

Never mind, maybe it's just me, I tend not to like too much text in apps.

**Comment by amulware** [comment]
When exactly should the notification be shown? And is there a case where the user would open the app before the notification is shown and still see this screen?

**Comment by pe0ny** [comment]
Let's show it 6pm like daily upvote/downvote ones.
When user opens the app before (eg 4pm, then we don't show anything yet). When user opens the app after 6pm, we'll show the popup.
I would keep the popup up until Monday noon, in case user didn't check it. I don't see a point showing this the whole week because users don't simply remember the last week then anymore.

**Comment by sofokli1** [comment]
I find it a bit confusing to use daily template to show weekly data especially when the user is already used to a weekly UI for these amount of data. Also how can someone judge something like this 
`Commute     15%      13h12min`
if it is correct or not? Also agree with @Odrakir regarding the amount of text.

**Comment by pe0ny** [comment]
@sofokli1 i get your point but showing the actual weekly summary there makes it too noisy. Maybe we should rethink it overall and maybe ask only rating to make it as clear as possible for users?
_I'll play with the design asap when i get back access to my sketch licence_

**Comment by pe0ny** [comment]
- Changed the copy a bit and cut 'Here is how your week looks like'.
- Use bottom part of the weekly summary. It still think it makes sense to show weekly summary when we're asking feedback about the whole week not only about the day. Showing the whole weekly summary with line chart would make thinks too noisy, so imo it's a nice alternative which gives user an overview and hopefully helps him/her to decide.
![weekly rating 1x](https://user-images.githubusercontent.com/5064445/29202135-b4c18a98-7e6d-11e7-8132-6a1fbe61b11d.png)

**Comment by amulware** [comment]
Q: instead of "Did the app.." maybe "Did Superday.."?

**Comment by pe0ny** [comment]
I like it! Yes, let's use Superday instead of 'the app' ;)

**Comment by sofokli1** [comment]
@pe0ny few questions:
- if the user does not open the app from the notification what should happen? (meaning it does not interact with the notification but just opens the app as usual)
- which part of the UI (with data) is scrollable? (does the title and message scroll? the pie chart?
- If the user closes the rating ui with the `x` button, how can the user vote at a later moment?

**Comment by pe0ny** [comment]
> If notifications are disabled, user will see a popup next time he/she opens the app.


* Pie chart together with data list is scrollable. Title + description and bottom part (with stars) are not.

* When user closes the popup, he/she can't vote later. No way to trigger popup manually.
