### ISSUE TITLE
Develop and test core motion prototype

### ISSUE THREAD

**Issue by amulware** [toggl/superday#697]
I _assume_ this will be done by @Odrakir. Since you know best what you have in mind, it would be great if you could give us a rough outline of the scope of the prototype, and what, if any help you need.

**Comment by Odrakir** [comment]
Ok, as I said I've been doing some tests and an app is already half done. I want to work a little bit more on it and give it some simple UI so you guys can test easily.

The basic idea is to be able to see the generated timeline and some configuration (thresholds and such) that would change in real time how that timeline is constructed. My idea is that this timeline is not persisted, and it's generated from raw data everytime, so you can see how it reacts to changes.

It would be cool if I also added some way of manually entering your time line, so you can compare, I'm leaving that for last.

My estimates are that in a week or two we could have something to play with.

**Comment by Odrakir** [comment]
More information soon, when I upload to GH.

**Comment by amulware** [comment]
Sounds good so far. Please proceed. :D

**Comment by Odrakir** [comment]
What do you mean proceed? Are we doing this right away?

**Comment by amulware** [comment]
Once the current milestone is through, yeah. At least part-time. Otherwise, it'll just take longer, and we'll need time to test and everything as well.

At least that was my thinking.

**Comment by Odrakir** [comment]
Ok, maybe I can focus on that while Eugene handles the next milestone (metrics, I guess). Let's do that.

**Comment by amulware** [comment]
Sounds good to me.

**Comment by amulware** [comment]
I'm not sure we still need this issue? Unless there is something more you wanna do here, feel free to close this, and the associated milestone as well.
