### ISSUE TITLE
Determine what exactly we can do with Fabric and alternatives

### ISSUE THREAD

**Issue by amulware** [toggl/superday#698]
As the title says, let's do a quick inventory of what Fabric allows us to do, and if this is not enough, what alternatives we have, and what relevant features they offer.

**Comment by sofokli1** [comment]
I played with mixpanel a bit today. From their material online is hard to see through the marketing (they say they are going to do everything for us apart from building the app itself). features wise i don't see much difference unless @Odrakir can point out something specific. The worst part is that we go with free they only keep 60 days worth of history and if we move to the next plan (100/month) we get only 12 months worth of history. We need to go to (1000/month) if we want unlimited history. I know i am not flipping the bill but i can't see the actual benefit at this point.

**Comment by Odrakir** [comment]
I had no idea it was so expensive. My guess is we could live with the 12 month history.

Mixpanel is great, but the question is: Are we going to use all its features? I think we first need to know which kind of stats we need and then find an affordable product that delivers. If we are not going to have somebody working on that specifically, probably Mixpanel is overkill.

**Comment by amulware** [comment]
@sofokli1 Is it worth writing down any of your findings here or otherwise? Otherwise feel free to close the issue.

**Comment by sofokli1** [comment]
Since i didn't find any concrete improvement compared to fabric for our needs, i am closing this
