### ISSUE TITLE
Prevent "Trying to create a negative duration TimeSlot" and "Failed to create new TimeSlot" warnings

### ISSUE THREAD

**Issue by amulware** [toggl/superday#709]
We are getting a lot of those. Our algorithms should be smart enough to not try and do this. I suspect there is some fundamental flaw where we have data older than the last slot in the current timeline, so we generate an overlapping TTL, which the time slot service refuses.

We should probably either ignore all data points from before the date the user last saw the timeline or at least scrap that data in the TTL before trying to persist it.

**Comment by pe0ny** [comment]
@amulware Is this still valid or can we close it?

**Comment by amulware** [comment]
THis was still occurring with 1.5.1 so I think it is still relevant.

**Comment by Odrakir** [comment]
We are completely changing the TL generation, so I'm closing this.
