### ISSUE TITLE
Fix location permission onboarding

### ISSUE THREAD

**Issue by amulware** [toggl/superday#712]
It appears that currently, it's not working at all.

We also most likely have to reposition the pointing emoji to point at the correct location for the updated permission notification (and this has to be different depending on which version the OS is).

**Comment by Odrakir** [comment]
![simulator screen shot - iphone 8 - 2017-09-13 at 10 31 55](https://user-images.githubusercontent.com/724743/30367545-cfd6049c-986e-11e7-94ce-c6a46a6ff537.png)

@pe0ny We also need design for this ☝️

**Comment by Odrakir** [comment]
Designs here: #725
