### ISSUE TITLE
Daily bar doesn't always collapse and expand correctly

### ISSUE THREAD

**Issue by sofokli1** [toggl/superday#715]
It is likely related to timelines with not many slots

![aug-09-2017 15-05-06](https://user-images.githubusercontent.com/885122/29120706-3cc59a5c-7d14-11e7-990a-3d0c491bb60b.gif)

**Comment by Odrakir** [comment]
In that case the bar should be expanded and never contract... How did you get to that point where it's contracted?

**Comment by sofokli1** [comment]
in combination with scrolling to other day were it can get shorter

**Comment by Odrakir** [comment]
I can't reproduce it, for me it always expands when coming back.

**Comment by pe0ny** [comment]
I can't reproduce either. Also, when it happens only with the timelines with out scrolling actually needed, I don't see it as an issue.
