### ISSUE TITLE
Rework onboarding for CM

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#725]
Ask user to give access for location and CoreMotion during the onboarding flow.
Don't allow user to proceed and use the app without.

**Comment by pe0ny** [comment]
- [ ] Remove asking permission to send notifications and replace it with CM permission.
- [ ] Ask permission to send notifications on the second day (24h hours after installing the app).

**Comment by Odrakir** [comment]
I've noticed this is not correctly align in all phones. Should I try to do it better or is it ok like this?

![img_3195](https://user-images.githubusercontent.com/724743/30322410-b1a7aa62-97b9-11e7-804a-fe0f0a1f9f96.PNG)
![img_3196](https://user-images.githubusercontent.com/724743/30322411-b1da9170-97b9-11e7-8261-18040f4c6004.PNG)

**Comment by pe0ny** [comment]
Don't you think it's super weird we have some parts translated and some are not? I would say we should pick one and stick to it. And for now it would make sense to stick to English.

**Comment by Odrakir** [comment]
I'll check, but I'm afraid there's nothing we can do about it. The first part of the message is in whichever language the user's phone is.

Other than that, what about my question?

**Comment by pe0ny** [comment]
Ok. About your question - let's keep it on hold until we have new copy for both screens. Then i'll check the designs and confirm with you :)

**Comment by pe0ny** [comment]
**Step3: location**
For iOS 10 and iOS11

![step3 1x](https://user-images.githubusercontent.com/5064445/30369481-5882e3b0-987d-11e7-9eba-48910efd627c.png) ![step3 ios 11 1x](https://user-images.githubusercontent.com/5064445/30369486-5c7a4602-987d-11e7-9888-f5b8d1f3efac.png)

**Step4: motion data**

![step4 1x](https://user-images.githubusercontent.com/5064445/30369521-759b85e2-987d-11e7-8dc3-ca9d7ebbcc96.png)

**Comment by Odrakir** [comment]
No text at the bottom for location in iOS 11?

**Comment by pe0ny** [comment]
No text

**Comment by Odrakir** [comment]
👍
