### ISSUE TITLE
Better display for movement 

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#727]
**Updated!**

- [x] Show movement slots as tags in the timeline so these take less space
- [x] Add labels to CM activities like: walk, run, cycle and transport
- [ ] User should be able to edit 'Movement' category in detail view #744 , not in timeline
- [x] User can't edit labels
- [x] 'Movement' can contain more than 1 movement slot
- [x] When movement slot contains more than 1 slot, show the number of slots next to the label

https://zpl.io/2vkeKrV

![timeline 1x](https://user-images.githubusercontent.com/5064445/30262017-e5cc5140-96d7-11e7-993f-73173ae2bdd2.png)

**Comment by amulware** [comment]
What you describe is literally just renaming the category, and nothing more really.

I think it would be nice if movement slots/groups get special treatment. Similar to how sleep is always minimum size, I would like movement to be even smaller, and almost disappear into the margins - but the user has to still be able to expand and edit it (maybe fitness is more appropriate, or travel, or commute, if we re-add those).

**Comment by Odrakir** [comment]
If I understand correctly Heidi is proposing collapsing different type of slots into a big movement one, so not the same as renaming. Right?

It's a pretty big change, but it can be done.

I also agree with making that slot even smaller.

**Comment by pe0ny** [comment]
@Odrakir is correct. and i agree with should display it differently (smaller or even somehow else) to use less space.

**Comment by amulware** [comment]
I don't see how that follows from what @pe0ny said above. If several slots in a row have the category 'movement' they will already be collapsed. 'walk', 'run' etc. should be displayed separately on the slot, and regardless of the category (fitness with 'running' makes perfect sense, as does work with 'driving', etc. this is up to the user, the movement category should just be an easy catch all for these until we have better guessing)

**Comment by Odrakir** [comment]
After the discussion on slack: 

Basically we are renaming Commute to Movement and for CM activities like run, cycle, walk and auto we'll tag the TimeSlot with them, but that has no effect in the category. Meaning that even if we by default set walk and auto to Movement and cycle and run to Fitness user will be able to change that category (although he won't change the tag).

The tag will show in the timeline as well. Design pending.

**Comment by Odrakir** [comment]
@pe0ny Can we get the colors without transparency? Right now you are using commuteBlue with 16% opacity for the category label, and then again over it for the amount of slots. But it'll be easier and better for performance to just get plain colors.

**Comment by Odrakir** [comment]
Never mind for now, Heidi, let's see how this behaves.

**Comment by pe0ny** [comment]
Just in case you need it:
#E6F8FC
and #D1F2F9

**Comment by Odrakir** [comment]
We need to think on what we do with the tags when dealing with a normal timeslot with different activity tags. Like in the screenshot the Fitness timeslot could be made of sub-timeslots with different activity types, not only "Run".

**Comment by pe0ny** [comment]
My proposal: if there is a normal time slot with different activity tags (like run, still, walk), I wouldn't display the label at all since user categorized it to something else already. But I would show labels in detail view.

**Comment by pe0ny** [comment]
Just to make sure: if normal time slot contains multiple slots, we should still indicate it (though user can't expand-collapse it the same we it was used to).

![timeline 1x](https://user-images.githubusercontent.com/5064445/31170981-de0e05ca-a906-11e7-9cfe-9709dce72502.png) ![timeline copy 2 1x](https://user-images.githubusercontent.com/5064445/31170985-e1ac48d6-a906-11e7-886f-d621c6ceb731.png)
