### ISSUE TITLE
Weekly user review crashes

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#737]
After getting notification and tapping on it, it tried to open the app and crashed before the timeline appeared.
I tried to open the app again, but it didn't show me any popup (though it should have when user haven't rated it yet), just regular timeline.

Can't say what happens when i open the app during the time when it should display the popup, with out interacting with the notification.

**Comment by sofokli1** [comment]
As far as i can tell based on Crashlytics the crash is not related to the weekly rating . Seems related to the pager for the timeline. Regarding the weekly rating not showing again there is a PR waiting for review for that.

**Comment by sofokli1** [comment]
@pe0ny if you don't see this happening, please close
