### ISSUE TITLE
Wrong time entry grouping over midnight

### ISSUE THREAD

**Issue by amulware** [toggl/superday#739]
Nevermind the extremely accurate categories, note the last slot which extends well past midnight.

![img_0746](https://user-images.githubusercontent.com/3987892/30018375-f1ce032e-915c-11e7-8b29-7e6d6c38ca85.PNG)

**Comment by sofokli1** [comment]
if you expand the slot is there a sub-slot that stops at midnight and one that starts at midnight?

**Comment by amulware** [comment]
There is one that ends at 29:59 and one that starts at 00:00 - it appears it includes only the first slot of the next day, and changing a <= into a < might be the fix.

**Comment by sofokli1** [comment]
@amulware if you want me to do something about this, add it to the milestone

**Comment by amulware** [comment]
Certainly. ;)

**Comment by sofokli1** [comment]
I thought you wanted this with `the metrics` release since there we introduce the cap at midnight

**Comment by amulware** [comment]
If you think this is an easy fix, we can do that too.

**Comment by amulware** [comment]
Makes sense to do it though, and not release this bug knowingly.
