### ISSUE TITLE
Record location on first run

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#743]
When the user first allows the app to get the location, we should get that location and store it, this is needed so the first CM slots already have a location assigned.

**Comment by Odrakir** [comment]
@pe0ny When the user gives us the location tracking authorization, I need to get the users first location. It takes some seconds, so I was thinking, we could show something like... "Finding you..." or whatever just behind the location authorization alert dialog, before going to the last onBoarding step.

Can we have a design for that?

**Comment by Odrakir** [comment]
By the way, we'll need something similar for the custom alert we have inside the timeline when the user didn't accept the authorization in the onboarding.

**Comment by pe0ny** [comment]
@Odrakir What is the difference of currently working app and the updated one? I mean currently we don't have any loader anywhere and it works fine.
- Though I like the idea having some loader in onbording
- But why we need this for that screen #753 because this directs user to the settings and it takes couple of seconds to navigate back to the app as well?

**Comment by Odrakir** [comment]
We need a loader because getting the user location takes a couple of seconds. In my current tests it's a little anoying that after pressing "Allow" the app is frozen for those 2 or 3 seconds.

Until now we were not doing this, because we weren't matching every timeslot with a location. We'll do that for now on with CoreMotion.

So we'll get the current location with GPS in two places:
- When the user first allows location tracking during onboarding
- When the user allows again location tracking in the custom alert

Both of them should take 2 or 3 seconds to respond after that.

**Comment by pe0ny** [comment]
> When the user allows again location tracking in the custom alert

By custom alert you mean this location disabled screen? So far we've been directing user to the settings where they can turn it on. Do you have anything else in mind?

**Comment by Odrakir** [comment]
Yep, I mean that screen. It goes to user settings, but when it comes back, and the alert disappears, it'll take us a couple of seconds to get the location.

Maybe we just need a global loading with a message.
