### ISSUE TITLE
Slot's detail view

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#744]
Previously user needed to tap on a time slot to edit the category.
Now when user taps on a time slot (either on a regular slot or movement slot) a detail view opens.

**Comment by Odrakir** [comment]
Designs, please :)

**Comment by pe0ny** [comment]
In zeplin 🎉

**Comment by pe0ny** [comment]
Let's enable only category editing atm. Next step would be editing start/stop times.

**Comment by sofokli1** [comment]
@pe0ny are you going to make a new issue for `Next step would be editing start/stop times.` so that we can close this one?

**Comment by pe0ny** [comment]
Yes 🙌
