### ISSUE TITLE
Use two linear functions to calculate the height of time slots

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#747]
Use two functions to increase slot’s height:
x = duration
y = slot's height
if x <= 60; y = 8/15x + 120/15
x > 60; -x + 13.5y = 480

slot's min height: 16pt

**Comment by Odrakir** [comment]
What's going on in the second equation?
Is it: y = (480 + x) / 13.5 
?

**Comment by pe0ny** [comment]
@Odrakir exactly ;)

**Comment by pe0ny** [comment]
Min height of the slot is 16pt

**Comment by pe0ny** [comment]
And let's try to use the same function for sleep slots as well
