### ISSUE TITLE
Location disabled screen

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#753]
Make sure to show this screen when:
a) User didn't allow access to location during the onboarding flow
b) Has turned off location from the settings
Don't allow user to proceed and use the app without enabling location.

PS: Atm it allows user to proceed by tapping 'Remind me later' button. This option should be removed.

![step5 location not enabled 1x](https://user-images.githubusercontent.com/5064445/30312276-6efad076-97a1-11e7-8231-d8fdf201a504.png)

**Comment by Odrakir** [comment]
So, in the end we are not allowing to use the app without location? I thought you said the opposite in slack :)

**Comment by pe0ny** [comment]
Yes. Let's try to keep the edge cases to minimum. We can always add it there if we actually see the need.

**Comment by Odrakir** [comment]
Ok, something else that needs to be done is: Until now we were only showing the custom alert once a day. I'm going to show it everytime the user disables location for now on.

**Comment by pe0ny** [comment]
Yes, it's a screen and it should be visible until the location is enabled.
