### ISSUE TITLE
Ask permission to send notifications on the second day

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#756]
Remove asking permission to send notifications from onboarding flow and ask permission on the second day (24 hours after installing the app).
For existing users don't ask this permission anymore (even if they don't have notifications allowed).
Trigger notifications popup when user taps 'Enable notifications'
User can tap 'No, thanks' to close this overlay

![enable notifications 1x](https://user-images.githubusercontent.com/5064445/30484433-07db0552-9a33-11e7-9a3a-63d5240d6ac1.png)

**Comment by amulware** [comment]
Just to make sure I get it: If a user does not come back to the app 24+ hours after first launch, they will never see this, and never see any notifications, correct?

**Comment by pe0ny** [comment]
When user never opens the app ever again, then yes, they won't see anything.
But when user comes back 2 days after the install or 5, 6, 7 etc.. then he/she can see this overlay.
