### ISSUE TITLE
Show loader when the user first allows location tracking during onboarding

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#757]
![step3 1x](https://user-images.githubusercontent.com/5064445/30319219-f71a8c1a-97b7-11e7-83b8-022796512460.png)

**Comment by Odrakir** [comment]
Just a note: It'll appear after dismissing the alert, so, we won't see both at the same time

**Comment by pe0ny** [comment]
@Odrakir ok, in that case I would go with this instead:
![step3 copy 2 1x](https://user-images.githubusercontent.com/5064445/30362348-40b606c2-9864-11e7-89e3-4d5e07631b83.png)

**Comment by Odrakir** [comment]
But why is everything so dark?

**Comment by pe0ny** [comment]
Because there will be another popup right after that, and we don't wanna make a disco where white and dark backgrounds are flashing 😛

**Comment by pe0ny** [comment]
And I would love to put all the text above this overlay but as far as i understood it's not possible since we're using system popups

**Comment by Odrakir** [comment]
Mmm... I'm afraid that's not going to work. Right now the dark overlay disappears (we have the disco and it's not so bad). I see two problems with what you propose:
- I have no way of knowing when the system overlay will disappear, so I don't know when to show the one you just designed. If I show both at the same time it'll be darker, if I show one a little bit after the other it'll be even more disco.
- It'd be cool if we could use this same loader for the other permissions request, the one in the timeline when you denied permissions here. And there's no system overlay there.

Finally, I don't know what you mean about the text. You can put text here, no problem with that.

**Comment by pe0ny** [comment]
Check: #761 
*We decided to find user's location after the onboarding flow*
