### ISSUE TITLE
Record location just before showing the timeline

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#761]
After the onboarding, if user enabled location, we'll need to get the user's current location before loading the timeline.

When the user enabled location not from the onboarding dialog, but from the custom alert in the timeline, we also need to get the current location.

A loading indicator is needed as this will take 2-3 seconds.

**Comment by pe0ny** [comment]
Show this overlay with loader:
a) When installed the app and enabled location during the onboarding
b) When user enabled location from the settings

![step5 locating 1x](https://user-images.githubusercontent.com/5064445/30367546-31c57dc4-9877-11e7-8b1c-09f4ccdea2a7.png) ![step5 location enabled 1x](https://user-images.githubusercontent.com/5064445/30367549-3427b1a4-9877-11e7-8f6b-78eb31985dbe.png)
*Steps after onboarding: loading state + done state*

![timeline location disabled 1x](https://user-images.githubusercontent.com/5064445/30367719-aa0dbfda-9877-11e7-880b-3508cbc6eedd.png) ![timeline locating 1x](https://user-images.githubusercontent.com/5064445/30367724-afffba1a-9877-11e7-9ab1-cce7b28e9612.png)
*Location is disabled - > user taps 'Enable location - > Directing user to the settings - > User enables location - > Loading state*
