### ISSUE TITLE
Onboarding views on bigger screens

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#770]
- [ ] On iphone6 and bigger screens, this text should be 56pt from the progress bar below:
<img width="316" alt="screen shot 2017-09-13 at 18 03 30" src="https://user-images.githubusercontent.com/5064445/30384777-e1de0a10-98ad-11e7-9b5e-fb2460fb0a33.png">

- [ ] Left/right emojis should be aligned middle on iphone6 and bigger screens:
<img width="319" alt="screen shot 2017-09-13 at 18 04 04" src="https://user-images.githubusercontent.com/5064445/30384809-fed8be76-98ad-11e7-96e2-f9183714f627.png">

*Check zeplin for additional info*

**Comment by Odrakir** [comment]
The left and right emojis are pointing to the incorrect option there ;)

**Comment by pe0ny** [comment]
@Odrakir haha, good point. changed the file in zeplin ;)
