### ISSUE TITLE
Notification for weekly rating is fired even in the first week of install

### ISSUE THREAD

**Issue by sofokli1** [toggl/superday#773]
Notification will fire for the first sunday in the week of the install but the UI will not show.

@pe0ny is it possible you experienced something like this?

**Comment by pe0ny** [comment]
@sofokli1 Honestly, I can't remember for sure. But i think this could be it - i remember the notification didn't trigger the popup.

**Comment by sofokli1** [comment]
Just for clarification and so that we are all on the same page. 

If UI (UI meaning `voting UI` or `weekly rating UI`) was only triggered by the notifications (meaning that they show only when notification is taped) things would be much simpler and all logic about when should we show this components would be in how we schedule notifications.

But since we need to the UI to show even if the user does not interact with the notification, the logic for presenting the UI is separate from the logic for scheduling notifications.

So notifications firing is just that, either the user taps on it or opens the app without taping the notification, the result is pretty much the same (both ways open the app). The only difference is that we will know if it was from a notification or not. This information is used for the daily voting to scroll to the date of the notification.

The logic for showing and scrolling to the bottom for the daily voting is in the `timeline` component, the logic to scroll to the correct date is in the `pager` component, the logic to show the weekly rating is in the `main` component.

So even if we remove notifications all together the UI will still show on the correct days and times.

Let me know if there is any question?

**Comment by pe0ny** [comment]
> If UI (UI meaning voting UI or weekly rating UI) was only triggered by the notifications (meaning that they show only when notification is taped) things would be much simpler and all logic about when should we show this components would be in how we schedule notifications.

Yes, but we can't rely **only** on notifications since we can't be sure these are enabled for everyone.

@sofokli1 Correct if I'm wrong but did I understand correctly that if we remove notifications all together, the logic will be simpler:
- **Voting UI:** We'll show this on the correct days and times
- **Weekly rating UI:** We'll show this on the correct days and times
Only difference is that Voting UI will be available users basically forever, while Weekly rating will be available only for 24h.

**Comment by sofokli1** [comment]
> Yes, but we can't rely only on notifications since we can't be sure these are enabled for everyone.
I understand and agree, i just described that scenario to explain why the current implementation is as it is now.

> @sofokli1 Correct if I'm wrong but did I understand correctly that if we remove notifications all together, the logic will be simpler:
what i am saying is that notifications about voting and rating are independent from the logic for showing voting and rating UI. So the voting and rating UI will work as you describe above with or without notifications.
