### ISSUE TITLE
Ask permission to motion data from existing users

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#774]
We need to ask access to motion data from existing users as well.

@Odrakir What are our options with HK - it would be nice to say to users we won't need access to their HK data anymore (because we don't) but is it actually possible to remove/disable HK access?

**Comment by pe0ny** [comment]
After user will update and open the app, I would like to show this screen, explaining why and what we need. User can't close or dismiss this popup.
When user taps 'Make Superday better' it should trigger the same alert we're using for onboarding.

If it's possible to remove/disable HK we should change the last sentence copy a bit to make sure we can't access their HK anymore.

![motion data access 1x](https://user-images.githubusercontent.com/5064445/30484039-c3f0c54e-9a31-11e7-94f5-c7fc02f60393.png)

**Comment by sofokli1** [comment]
I think it should be `Health Kit` instead of `Health App` but i am ok either ways

**Comment by pe0ny** [comment]
The reason behind it is because we used 'Health app' when we first ask permission to it. I think it makes sense to use the same wording.
And the reason why we didn't use 'Health Kit' at first place was because we tested it on people and they had no idea what is Health Kit. 😛 (I guess it's something we know but end-users don't)

**Comment by Odrakir** [comment]
I agree it's better to use "Health App", the term is more user friendly.

Eugene, this issue will also involve removing the HK entitlements from the provisioning profiles.

**Comment by sofokli1** [comment]
since there is a lot of HK stuff, HK clean up should be on an issue of it own.
