### ISSUE TITLE
Rename 'Commute' to 'Movement'

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#777]
Rename 'Commute' to 'Movement' but keep everything else the same. Meaning we won't add labels in this versions; timeline will look the same just with different category name.

**Comment by sofokli1** [comment]
@pe0ny will the image change as well or just the name?

**Comment by pe0ny** [comment]
@sofokli1 Just the name :)

**Comment by pe0ny** [comment]
Also, let's make sure it's called 'Movement' in daily and weekly summary as well.
