### ISSUE TITLE
Metrics needed

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#8]
- [x] Number of downloads through lifetime of the app (that we can get from itunes connect)
- [x] Number of uninstalls through lifetime of the app
- [x] Number of unique sessions (the number of times the app has been used for at least two seconds)
- [x] Number of total sessions (the number of times the app has been used for at least two seconds by all users) daily/weekly/monthly
- [x] Time spent per session to measure user engagement of the app (similar to bounce rate)
- [x] Conversion rate = app openings/total downloads
- [x] Rating

**Comment by pe0ny** [comment]
And we want to measure usage of:
- [ ] Edit function
- [ ] Switch function ('+' button)

**Comment by willsb** [comment]
PR #12 adds most of the needed functionality. We can use HockeyApp's custom events to add the Edit/Create button events, once we have the proper UI for them. I just need to figure out if Hockey App gives us the time spent on each session.

**Comment by amulware** [comment]
Blocked by #7
