### ISSUE TITLE
Fix smart guesses

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#800]
Up for discussion how can we fix smart guesses which is currently disabled.

**Comment by Odrakir** [comment]
I think we can try with something in the general direction of what we were doing, but with a different approach. I don't have the specifics now, but instead of taking every slot as a single thing, we should see how it fits within each day... 

I'm just throwing stuff out there.

Let's think about it.

**Comment by pe0ny** [comment]
Some ideas I had:

a) Use only location not date & time (I believe it should be pretty easy since we're already using location and now each time slot has location as well).

b) Use google API to assign categories.

**Comment by sofokli1** [comment]
based on the comments i see, i think this should be in the `Super-Smart` milestone?

**Comment by pe0ny** [comment]
As we decided last week, we're going to ditch smart guesses DB and going to use previous timeline to guess.

**Comment by sofokli1** [comment]
using only GPS data only, without time data?

**Comment by amulware** [comment]
Please also note information in #730

**Comment by amulware** [comment]
In general, I would very much like to ditch the existing system entirely and implement a much simpler system taking into account the last 2 (or so?) weeks of data, with simple weighing by location-distance.

Please make sure that all timeslots have locations as well for this.

**Comment by sofokli1** [comment]
in the spirit of moving things forward faster, this could be achieved just by removing the date part of the current smartguess logic and changing the date filtering to 2 weeks (even though i would say that a bit longer wouldn't hurt, like 1month). How does this sound?

**Comment by amulware** [comment]
But that will still use the current smart guess database then, right? I really think we should burn that.

**Comment by amulware** [comment]
I'd rather go for the rewrite anyways since we'll have to do so sooner or later in either case.
