### ISSUE TITLE
Update to Swift 4.0

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#801]
Not only our code, but also the libraries we are using. So it'll need some testing.

**Comment by Odrakir** [comment]
Let's check what's the state on the 3rd party libraries first to see if it makes sense to do it now.

**Comment by sofokli1** [comment]
All pods can be updated to swift 4 but some may introduce API changes. In some cases we are more than 1 major version behind.

**Comment by Odrakir** [comment]
Ok, let's move this to its own milestone.

**Comment by Odrakir** [comment]
Some literature to help with this:
https://swift.org/migration-guide-swift4/
https://medium.com/@timefrancesco/swift-4-migration-and-cocoapods-31e5ac020980
