### ISSUE TITLE
Really long 0 min time slot

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#811]
After installing the app or when creating new time slot manually, it's very long though it should be only 16pt.

![img-4398](https://user-images.githubusercontent.com/5064445/31556841-4b94dbce-b04f-11e7-91b5-f65a9283f6ac.PNG)

**Comment by pe0ny** [comment]
@sofokli1 I believe it's fixed? I can't manage to reproduce it anymore. How about you?

**Comment by sofokli1** [comment]
i fixed it
