### ISSUE TITLE
Detail view: edit start/stop times

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#814]
- User can edit start and stop times by tapping on a start/stop time in edit view
- When editing start time, show previous slot as well
- When editing stop time, show next slot
- Don't allow editing stop time for currently running time slot
- Use handle to slide up/down
- Popup is constrained to the sides (20pt from top and 16 from the bottom); not to a certain height; so the height should change based on the device size.
- Increase time slots's heights proportionally so they'll cover the popup.

<img width="702" alt="screen shot 2017-10-27 at 09 52 30" src="https://user-images.githubusercontent.com/5064445/32091478-05b427c8-bafd-11e7-93c0-4c32f51f11f2.png">

**Comment by pe0ny** [comment]
I see your point but then we should change this logic everywhere (eg in edit view, popups etc). Let's keep it as it is for now but i'll think about it.

**Comment by Odrakir** [comment]
Ok, another thing: We can't draw over the status bar, so we can't put that white overlay there.

What I'll do, if it's ok with you, is lower the popup a little bit so you can kind of see the app header.

![img_4d4f82c1ef9c-1](https://user-images.githubusercontent.com/724743/32553096-3108ffe6-c496-11e7-9731-aacf9725eb6e.jpeg)

**Comment by pe0ny** [comment]
@Odrakir Yes, sure. 👍 and sorry, i know that we can't put anything on top of the statusbar but somehow i missed to reorganize layers.

**Comment by Odrakir** [comment]
One more thing, does the color of the handle match the category of the slot you are trying to edit or is it always yellow?

**Comment by pe0ny** [comment]
It should match the slot's color user tries to edit.
