### ISSUE TITLE
New goal popup

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#825]
To set a goal user have to pick:
- how much time he/she wants to spend on it (30min, 45min, 1h, 1.5h, 2h, 3, 4, 5, 6, 7, 8, 9, 10h)
- on what he/she wants to spend time (pick a category)

Other notes:
- user can slide durations and categories from left to right and from right to left (similar how current editing categories works)
- tapping 'Set a goal' button takes users to Goals view

![goal popup 1x](https://user-images.githubusercontent.com/5064445/31873634-34eac80e-b7cd-11e7-8de4-1ff7df774c6a.png)

**Comment by amulware** [comment]
Just a thought on the design: I find the 'I want to...' sentence a bit hard to read over the heavy headline, while I think that from a UX point of view it should be the main thing, to really make the user say, in their head 'I want to do X' to make them more likely to mean it and to do it.

I would almost argue to swap the fonts between the two.

**Comment by sofokli1** [comment]
@pe0ny 
- Which value is the default in the hours picker?
- What are the exact values for the hours picker?
- Should the categories picker wrap around? (IMO if the hours do not wrap around, so should the categories)

**Comment by pe0ny** [comment]
1) 1h
2) values should be: 30min, 45min, 1h, 1.5h, 2h, 3, 4, 5, 6, 7, 8, 9, 10h also mentioned above or do you mean something else?
3) both categories and hours picker should wrap around
