### ISSUE TITLE
'Set a goal' reminder in Timeline view

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#826]
- When user hasn't set up a goal yet, show this reminder in Timeline view
- When user taps on it, open a new goal popup
- When user swipes it down, remove this reminder from Timeline view and don't show it anymore on that day (show it again on the next day when user hasn't set up a goal yet)

![timeline goal 1x](https://user-images.githubusercontent.com/5064445/31873782-1b6a2d88-b7ce-11e7-83ea-2678c04039ac.png)

**Comment by Odrakir** [comment]
We are doing only daily goals, right? If it's already after 7 PM (for example) when the user opens the app... Does it make sense for him to make a goal for tomorrow instead?

I find it useless to show that reminder by the end of the day. And also it's a little inconvenient having to set the goal early on the same day you are trying to accomplish it (as opposed to do it the night before)

**Comment by pe0ny** [comment]
Yes, we're doing only daily goals. You mean we should allow setting a goal for tomorrow only when user achieved today's goal? Because I wouldn't let user to set a new goal when today's goal is WIP or when user haven't set a goal for today at all. Also, I wouldn't say it's useless to ask user to set a goal after 7PM since users's daily routines are rather different (making an assumption here).

**Comment by Odrakir** [comment]
Mmmm... ok.
