### ISSUE TITLE
Goal achieved view

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#827]
- Show it immediately in the app when when user achieved the goal.
- User can either see his/her score
a) By checking his/her phone - if goal achieved, we'll display it right away
b) By notification if user didn't check his/her phone on the last day #830 

- Generate random copy every time when user achieves the goal. (List of copies will increase in the future) Show this only when user opens the app on the same day: 👇

- **First goal achieved:**
a) You did it! + trophy First goal achieved.

- **List of copies part 1:**
a) Daily goal achieved + trophy
b) Daily goal achieved + tada
c) Goal achieved + trophy
d) Goal achieved + tada

- **List of copies part2:**
When user checks his/her phone before 5pm:
a) Enjoy your day.
b) You're all all done for today!
c) You absolutely nailed it, good job!
d) Another goal bites the dust - nice work! 
e) Keep doing what you’re doing 🙌
f) Nice going there!
When user checks his/her phone after 5pm:
a) Enjoy your evening.
b) Enjoy your night.
c) You're all all done for today!
d) You absolutely nailed it, good job!
e) Another goal bites the dust - nice work! 
f) Keep doing what you’re doing 🙌
g) Nice going there!

- **For over achievement (when user did 200% or more) show only:**
a) Daily Goal - Smashed to pieces.
b) Damn, you’re not kidding around.
c) Daily goal achieved + trophy Look at you all organized and productive.
d) Daily Goal - Done & then some.
e) Daily Goal - Neutralized.

![goals - achieved v1 1x](https://user-images.githubusercontent.com/5064445/32213991-183bf462-be26-11e7-87c6-b40a8a2d8ef4.png)

**Comment by sofokli1** [comment]
@pe0ny what does the part1 and part2 mean?

**Comment by pe0ny** [comment]
@sofokli1 I would like to pick randomly one part of the copy from part1 and another part randomly from part2. In that case user won't see the very same thing all the time when goal is achieved. For example:
From part1 a) and from part2 b): Daily goal achieved + trophy You're all all done for today!

**Comment by pe0ny** [comment]
Let me know if this gets too complicated. I can try and create one list as well.

**Comment by sofokli1** [comment]
it's ok, i get it now

**Comment by sofokli1** [comment]
What about this (or something similar):

Goal achieved 🏆
You go have a superday now!
or
You just tasted a superday!
