### ISSUE TITLE
Goal failed view

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#828]
- Wait until midnight before displaying failure in the app. (When user achieved the goal, show it immediately).
- User can either see his/her score
a) By checking his/her phone after midnight or after that
b) By notification if user didn't check his/her phone on the last day #830

**Comment by pe0ny** [comment]
- **When user missed more than 10%:**
a) You missed your goal by 24%. Don’t worry, we’ll get him next time!
b) You finished 76% of your goal - nice! How about we make it 100% today?

- **When user missed 10% or less:**
a) Ahh, so close - don’t give up now!
b) Seems you missed your goal. Not to worry, happens to best of us.
c) Oh no, missed it by this 👌 much! Keep trying, you’re almost there!

- **When didn't do anything - 0%:**
a) Knock, knock! Who’s there?  Your unfinished goal from yesterday.
b) This goal says it’s yours and that you forgot about him.
c) You know goals come back to haunt you?
d) Nothing to see here, move along.
e) Is it just us or you haven’t tracked your goal yesterday at all?

![goals v3 fail 1x](https://user-images.githubusercontent.com/5064445/32551193-61efe7ee-c498-11e7-923f-931c7548747f.png)

**Comment by amulware** [comment]
Grammar:
> Seems you missed your goal. Not to worry, happens to THE best of us.

> Is it just us or DIDN'T you track your goal AT ALL yesterday?

;)

**Comment by pe0ny** [comment]
Thanks 🙌
