### ISSUE TITLE
Inform the user about the results on the next day

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#830]
If user has not yet seen his/her results, send a notification on the next day saying: 'Results are in for September 24. Check it out'.

![goals - notification v1 1x](https://user-images.githubusercontent.com/5064445/32214360-3e439862-be27-11e7-8778-bf6c1ac87218.png)

**Comment by Odrakir** [comment]
So, this shows when the user has set a Goal for a day, on the next day, if he hasn't yet checked the results... At what time, @pe0ny ?

**Comment by pe0ny** [comment]
Yes - if user hasn't checked the results yet. Let's fire this notification at 11am
