### ISSUE TITLE
Ask to enable notifications if disabled

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#832]
- Right after when user has set his/her first goal (and *if* notifications are currently disabled), ask user to enable notifications.
- Ask this only once, after setting first goal.
- User can close the popup by tapping 'x' at the top right corner.
- Don't direct user to the iOS global settings, instead open the alert.

![goals - notification 1x](https://user-images.githubusercontent.com/5064445/32838728-a6e15fd6-ca1a-11e7-8323-bba7235b653d.png)

**Comment by sofokli1** [comment]
@pe0ny in a previous milestone we introduced the option for the users to say no to notifications. what should we do about those users in this situation

**Comment by pe0ny** [comment]
@sofokli1 we can always ask again :) they can close the popup if they don't want to get notifications.
