### ISSUE TITLE
Remind user to work on his/her goal

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#834]
- Send notification 3 hours after the goal has been set if user set the goal before 8pm.
- When user set the goal after 8pm, don't send any notification after that.
- Show content based on which category user picked. Note: There'll be general notifications as well.

Family:
a) Spent some quality time with your Family already? Don’t forget your goal for today!
b) Always nice to squeeze some extra family time when possible. And also to check your goal status!

Fitness:
a) So what you’re doing today, cardio or some power training? Check how your Fitness goal is progressing.
b) You like to move it, move it? We like to track it, track it.
c) Time to move on. Or generally move a bit. Check your daily goal.

Food:
a) Mmmmmm, I think I’m up for some pizza. You? Remember to check your goal!

Leisure:
a) Finally, leisure time! What’s it gonna be – Netflix or games? Or both 😈?

Movement:
a) You like to move it, move it? We like to track it, track it.
b) Time to move on. Or generally move a bit. Check your daily goal.

Work:
a) Remember to do some work, work, work, work, work. And also check your goal, goal, goal, goal, goal!
b) Heigh-ho, heigh-ho, remember to do your work goal. See your progress.

Shopping:
a) Hide yo’ kids, hide yo’ credit cards. Just kidding, got some some shopping done today?

**Comment by Odrakir** [comment]
@pe0ny What about the general ones?

**Comment by pe0ny** [comment]
@Odrakir For now we don't have more than posted above. Also, general ones will come in upcoming releases.
