### ISSUE TITLE
Give suggestions when user failed to achieve the goal

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#835]
**List of suggestions** when user failed to achieve the goal and opens the app afterwards #828 :

**When user set a goal for 2 hours or more, suggest to try X/2 hours instead:**
a) Remember, small steps will take you there. Maybe try with N hour(s) instead for a start.
b) That was a nice try, but to get the ball rolling, maybe try doing <goal-icon> for N hour(s) instead.

**When user started his/her day after 9:30AM:**
*Question to devs: Can we use the first slot after the sleep slot to detect this?*
a) Hey there sleepyhead - how about we try doing some goals earlier in the day?
b) Get things done early in the morning. Remember - Early 🐦 gets 💩 done!

![goals failed with suggestion 1x](https://user-images.githubusercontent.com/5064445/32551910-c8135e78-c49a-11e7-8be9-557ad72750d6.png)

**Comment by Odrakir** [comment]
Just in case I'm not the one coding this. This should be done subclassing the custom `Alert` class added in PR #889, for an example of its usage you can check #890

**Comment by Odrakir** [comment]
@pe0ny For after 9:30 suggestions... Do you want to check if there's any movement at all before 9:30 or if there's any activity on the goal category before 9:30?

**Comment by pe0ny** [comment]
@Odrakir I think it's a good idea: to check if before 9:30 there aren't any movement or goal category slots, and show this suggestion only then.
