### ISSUE TITLE
Settings view

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#837]
- Submit Feedback: Open already existing feedback form
- Rate Superday: Direct user to the App Store and open 'Write a Review'
- Help: Direct user to KB (*link will be added here*)
- Show version number at the bottom of the screen

Design: https://zpl.io/aRMw7Yz

**Comment by georgmay** [comment]
@pe0ny please add the KB link

**Comment by pe0ny** [comment]
@georgmay here it is: https://support.toggl.com/superday/ 😊
