### ISSUE TITLE
Tab bar colors don't match design

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#853]
The selection color of the buttons is another kind of blue and the separator line is too dark.

Also, this is a suggestion, but I would move all the tab bar code to it's own subclass.

**Comment by sofokli1** [comment]
how about just a presenter for the tabBar that does all the boilerplate code and just returns the tabBar with all the needed VCs?

**Comment by Odrakir** [comment]
I think we can do something similar to what NavigationPresenter does, is that what you mean?

**Comment by sofokli1** [comment]
yes
