### ISSUE TITLE
Timeslot detail view takes too long to appear

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#858]
The first time you tap on a timeslot (after completely closing and opening the app back again), it takes about a second or more for the detail view to appear.

**Comment by Odrakir** [comment]
I'm moving this to the daily goals milestone because now, for some reason, it's taking like 5 seconds or so.

**Comment by sofokli1** [comment]
device or simulator?

**Comment by Odrakir** [comment]
Device, with app store version it takes about a second. With "develop" version in debug mode it's taking 5 seconds now.

**Comment by sofokli1** [comment]
@Odrakir can you make videos? i can't reproduce on device

**Comment by Odrakir** [comment]
This seems to be happening only in debug builds 🤷‍♂️ 

Closing it for now.

**Comment by Odrakir** [comment]
No, this still happens in the Testflight build. The first detail view I open after starting the app takes about 4-5 seconds in my phone.
