### ISSUE TITLE
View goes black when changing tabs

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#859]
If I show a detail time slot view, change to another tab without closing it, and go back, the view is black.

Even if we fix this, which shouldn't be hard, I think it makes sense for the whole popup to appear over the tab bar, so this is just not possible.

![img_3905](https://user-images.githubusercontent.com/724743/32546139-59783d60-c47e-11e7-826e-3141ba2a376d.PNG)

**Comment by sofokli1** [comment]
@pe0ny what would you say if the edit view covers the tabBar?

**Comment by pe0ny** [comment]
It would actually makes sense to me when edit view covers the tab bar
