### ISSUE TITLE
Make sure nav bar is visible in every view

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#862]
- [x] Nav bar should be visible in all views: Timeline, Goals, Reports, Settings
- [x] Nav bar paddings from left and right should be: 16pt from left and 8pt from right
- [x] Superday text should be 12pt from the Superday icon
- [x] Show Calendar icon only in Timeline view (Not in Goals or Reports).
- [x] Calendar icon colour should be #B7B9BB

![timeline 1x](https://user-images.githubusercontent.com/5064445/32603581-eb862bde-c552-11e7-9189-92ab81cf86d2.png)

**Comment by pe0ny** [comment]
About second point: it should be 16pt from **left** and 8pt from **right** 🙈

**Comment by georgmay** [comment]
>  Calendar icon colour should be #B7B9BB
@pe0ny please update the one in Zeplin

**Comment by pe0ny** [comment]
@georgmay 

1) It's available in here: https://zpl.io/bPqLQJD

2) Icon is not a font, it's this circle thingy *(so distance between icon/logo and text should be 12pt)*:
Sorry, for not making that one clear.

<img width="326" alt="screen shot 2017-11-13 at 19 28 40" src="https://user-images.githubusercontent.com/5064445/32739560-e2fb6a98-c8a8-11e7-87c4-9863c7825567.png">

**Comment by georgmay** [comment]
@pe0ny 

*Superday text should be 12pt* from the Superday icon

Ah you meant the *distance* between the text and icon? Gotcha.
