### ISSUE TITLE
Edit start/stop times: indicate deletion

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#876]
Use bin icon to indicate the time slot being deleted
Zeplin: https://zpl.io/bzwkxjz

![edit start-stop time delete 1x](https://user-images.githubusercontent.com/5064445/32731847-9018abe8-c893-11e7-9455-1d74f4d99c7c.png)

**Comment by Odrakir** [comment]
@pe0ny please, the trashcan icon... Can I have it as a black png (100% opacity) with transparent background?

**Comment by pe0ny** [comment]
Updated zeplin file: https://zpl.io/bPqLQJD
