### ISSUE TITLE
Issues in Settings

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#891]
The Settings tab:
- Doesn't quite match the design (the header is bigger in design)
- Should (probably) also include the header shadow
- Is missing the build version at the bottom
- The feedback button in the nav bar should be removed for the whole app.

**Comment by sofokli1** [comment]
your last point should be a separate issue

**Comment by Odrakir** [comment]
I don't think so. That button has to go the moment we introduce the same functionality in Settings.

**Comment by sofokli1** [comment]
i was thinking of splitting it so that 2 people can work on it, but ok
