### ISSUE TITLE
Duration inconsistency for last slot from yesterday when no new slot is created for today

### ISSUE THREAD

**Issue by sofokli1** [toggl/superday#905]
It doesn't cap at midnight in the edit view.
is this worth fixing?

also @pe0ny in the last image the `end` field does not have a value. is that ok?

![simulator screen shot - iphone x - 2017-11-28 at 12 04 56](https://user-images.githubusercontent.com/885122/33313928-649186a8-d42c-11e7-802a-ef1abc4cc534.png)
![simulator screen shot - iphone x - 2017-11-28 at 12 07 51](https://user-images.githubusercontent.com/885122/33313932-677a2ffa-d42c-11e7-9341-60c7422cef2f.png)
![simulator screen shot - iphone x - 2017-11-28 at 12 07 53](https://user-images.githubusercontent.com/885122/33313936-699cb910-d42c-11e7-80af-97de8e3519a0.png)

**Comment by pe0ny** [comment]
Do I understand correctly that in Timeline it shows duration 7h 31min and in edit view it shows 19 h 39 min?

**Comment by Odrakir** [comment]
How can this happen? Today should have a slot always, right? Did you mess with start/end times in a buggy version?

**Comment by pe0ny** [comment]
> also @pe0ny in the last image the end field does not have a value. is that ok?

Nope, it's not ok. It should have an end value but user can't just edit last slot's end time, but it should be visible.

**Comment by sofokli1** [comment]
> Do I understand correctly that in Timeline it shows duration 7h 31min and in edit view it shows 19 h 39 min?

Yes you understand correctly. Timeline caps at midnight, but edit view doe not.

> How can this happen? Today should have a slot always, right? Did you mess with start/end times in a buggy version?

This is simulator so no coremotion. That is why i asked if it is worth fixing.

**Comment by Odrakir** [comment]
Even in simulator it should add a slot for the start of the day if there isn't any coming from CM. My guess is your DB was corrupt due to testing.

I'd say it's not worth fixing, because this can't really happen and also because we should eventually remove end times.

Maybe we should try to make this work better in simulator, mocking CM or something, but that's a entirely different problem.
