### ISSUE TITLE
Replace Fabric Answers with Firebase for analytics

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#917]
Firebase brings more features for analyzing that info, so we need to move to it.

Instructions: https://firebase.google.com/docs/analytics/ios/start

**Comment by amulware** [comment]
Note that we already have some stuff setup for the toggl apps, so please coodinate with me here.

**Comment by sofokli1** [comment]
@Odrakir are we removing `Crashlytics` as well?

**Comment by sofokli1** [comment]
i am using this as an answer 
![screen shot 2017-12-08 at 13 25 34](https://user-images.githubusercontent.com/885122/33764013-5afa9250-dc1b-11e7-8697-bc5ea54e0236.png)
