### ISSUE TITLE
Track of how many users set a goal

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#920]
We want to know of how many active users (daily actives) set goals.

**Comment by sofokli1** [comment]
@pe0ny are we interested in which category and/or duration did the user choose?

**Comment by pe0ny** [comment]
@sofokli1 I think we don't need to know the category especially because soon we'll add custom categories anyways. Though duration would be good to know. I'll make an issue for that.

**Comment by sofokli1** [comment]
@pe0ny wouldn't this issue be resolved by the count of events in issue #923, or do you want these separately?

**Comment by pe0ny** [comment]
@sofokli1 You are correct that we need this issue's data to solve #923 but in Firebase I would like to see these numbers separately as well:
a) how many users set a goal
b) which durations were chosen of those who set the goal and
- achieved the goal
- failed

**Comment by sofokli1** [comment]
@pe0ny do we want to measure goal edits?

**Comment by pe0ny** [comment]
@sofokli1 yes! let's add this one as well 🙌
