### ISSUE TITLE
Change location permission copy

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#924]
<img width="226" alt="screen shot 2017-11-30 at 08 39 18" src="https://user-images.githubusercontent.com/5064445/33417568-b5a6db2c-d5aa-11e7-97ff-1573ada8a0be.png">

Change the copy back to:
"We need to access your location to generate your daily timeline."

**Comment by Odrakir** [comment]
Finally "We need to access your location to generate your daily timeline"
