### ISSUE TITLE
Calendar days don't show correct colors

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#933]
It happens often when moving between months.

As you can see the first screenshot is missing all days, the second (after moving to November and back) still misses Monday and Tuesday.

![img_4088](https://user-images.githubusercontent.com/724743/33701391-dd06e2ec-db1e-11e7-837c-19cfab2ef465.JPG)

**Comment by sofokli1** [comment]
i am finding this hard to reproduce. any idea?

**Comment by sofokli1** [comment]
Regarding the slow opening of the calendar, I think it is related to the pod. When it is initialised it loads the calendar month for the startDate and scroll without animation to the last month (today) and as it does this it loads all the months in between and all the cells for those months. So in theory the longer you have the app the longer it will take to open the calendar.

**Comment by Odrakir** [comment]
We might need to consider rolling our own calendar, it's not so hard.

What about the bug with some days not getting correct slots?

**Comment by sofokli1** [comment]
> What about the bug with some days not getting correct slots?
I do not have a solution yet
