### ISSUE TITLE
Allow expanding/collapsing time slots again

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#947]
- [ ] Tapping a slot that contains more than one slot, expands this slot.
- [ ] Tapping the arrow at the bottom, collapses the slot again.
- [ ] Each expanded slot is tappable and opens edit view of this specific slot. _This means edit view is only for one slot only, not for multiple slots anymore._
- [ ] Both, regular and movement slots are expandable/collapsible.
- [ ] Do not show start time or total duration next to the main slot when slots are expanded. Start time and duration will be displayed next to each expanded slot.

### Expanded regular slot
![timeline - expanded regular slot 1x](https://user-images.githubusercontent.com/5064445/33998001-e9afc07e-e0ee-11e7-992c-3b8075d270c9.png)

Zeplin: https://zpl.io/VQMpzN5

### Expanded movement slot
![timeline - expanded movement slot 1x](https://user-images.githubusercontent.com/5064445/33998009-efa9fb5c-e0ee-11e7-9717-9390aaeb7028.png)

Zeplin: https://zpl.io/bAO6PRp

**Comment by Odrakir** [comment]
Please rescue the code that already did this from version control. All we need to change is the UI a little bit.
