### ISSUE TITLE
Locations are not working

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#948]
There's something wrong with the persistence at some point. The logs show all the locations, but the DB only stores one, so that's the only one users ever see.

**Comment by mzgnr** [comment]
If noone working on this, i think i can send a PR

**Comment by Odrakir** [comment]
It's on our current milestone, but no one is working on it just yet. You are welcome to propose a fix. Thanks.

**Comment by sofokli1** [comment]
@Odrakir not sure if it is related to the issue but wanted to ask about this.
shouldn't the `reduce` [here](https://github.com/toggl/superday/blob/develop/teferi/TimelineGenerator/Helpers/EventAnnotator.swift#L46)
be more like this:
`locations = locations
                .reduce([]) { (acc, location) -> [Location] in
                    guard let lastLocation = acc.last else { return [location] }
                    guard self.isValid(location, previousLocation: lastLocation) else { return acc }
                    return acc + [location]
            }`

**Comment by Odrakir** [comment]
Oh my! That doesn't look right at all. Let me push a fix and make that code a little bit clearer.
