### ISSUE TITLE
Goals disappear

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#965]
I haven't opened the app for a couple of days and all my previous goals have disappeared. Tbh, I don't know how to reproduce but any ideas on this?

**Comment by sofokli1** [comment]
@pe0ny 
- Are you sure you din't do a fresh install at some point?
- When was the app installed? (you can check how far back the calendar goes)

This is very strange because we do not even have code that can delete the goals

**Comment by pe0ny** [comment]
@sofokli1 

That I'm sure of. The calendar goes back to Nov 3rd, 2017. I've updated the app quite a lot but never done a clean install.
