### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by pe0ny** [toggl/superday#973]
1. Disable notifications manually from your phone settings.
2. Open the app on the second day.
3. App asks to enable notifications. Pick 'No, thanks':
![img_4971](https://user-images.githubusercontent.com/5064445/35331233-3ea29bac-010f-11e8-8b4f-5dd6a6d5a7a0.png)

4. Navigate to 'Goals'
5. Navigate back to 'Timeline'
6. This appears, again (being a bit broken):
![img_4972](https://user-images.githubusercontent.com/5064445/35331235-42609208-010f-11e8-8e89-d28ccdd64613.png)
*After a while, 'No, thanks' option appears again and when I select it, the overlay closes. Though, when I repeat step 4, the overlay appears again in Timeline view.*

- For me, it happens only when I disable notifications manually from the phone settings
- This happens with current app store version and the latest build as well
- I'm using SE and iOS 11.2.1

**Comment by sofokli1** [comment]
@pe0ny Are the buttons not showing text the only issue?

**Comment by pe0ny** [comment]
@sofokli1 Nope, the issue is that overlay shouldn't be shown at all.
As stated here #756 we show this only once on the second day after the install. We shouldn't ask this when user turns off notifications manually.
And another case is this #832 when we ask to enable notifications (if disabled) after setting a goal.

**Comment by sofokli1** [comment]
@pe0ny If the user selects `No, thanks` in timeline, do we still ask for notifications after setting a goal?

**Comment by pe0ny** [comment]
@sofokli1 yes, but only once.
