### ISSUE TITLE
Script to populate Motion Event database

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#978]
The first time the user runs the app with the new algo, we have to get the CM data for the last week and populate with it the motion event table.

**Comment by sofokli1** [comment]
@Odrakir For this I was thinking to add a settings that keeps the last timestamp from the last motion data that we get and use this to keep track of the period of coreMotion data that we need next time the app opens. Create an Interactor `ImportMotionEventInteractor` that loads motion event from the os (using the setting for the date) and saves those to Coredata. For the saving, it creates `MotionEventPM` objects and implement the `encode` func. What do you think?

**Comment by Odrakir** [comment]
That's perfect. Just some details things:
- The name shouldn't include the word "Interactor" `ImportMotionEvents` is better
- If the user never executed this, it should get last week of motion events (or since app install)
- Did you consider checking the last date in the DB instead of adding another setting? Just a thought

**Comment by sofokli1** [comment]
@Odrakir 
I agree with your points.

I think we also need a `static func store<B: PersistencyModel>() -> CoreDataResource<[B]>` and `static func store<B: PersistencyModel>() -> CoreDataResource<B>` in `CoreDataResource`

also somthing like `func save<A>(_ resource: CoreDataResource<A>) -> Observable<A>` in `CoreDataPersistency`

Does this make sense?

**Comment by Odrakir** [comment]
Mmm... I think we just need a new method in `CoreDataPersistency`. Something like:
```swift
func create<A: PersistencyModel>(_ model: A) -> Observable<A>
```

You'll probly need to change the `encode`signature on `PersistencyModel` so it accepts a `NSManagedObject` or a `MOC`

**Comment by Odrakir** [comment]
Should we do all that in a different PR?
