### ISSUE TITLE
Category selector in new goal popup is slow

### ISSUE THREAD

**Issue by Odrakir** [toggl/superday#991]
When you add a new goal, the category selector is really slow, or rather it runs at low FPS. The time selector is fine, though

**Comment by sofokli1** [comment]
I can say that I have experienced this in the past but I can't reproduce in the latest build for some unknown reason. @Odrakir can you check with the latest build from tesflight?

**Comment by Odrakir** [comment]
The last build from Test Flight still has this problem.

**Comment by juanlaube** [comment]
I couldn't reproduce this on the App Store version (build 949), neither on ad hoc build.
